### ISSUE TITLE
no QosHandler found in DI container

### ISSUE THREAD

**Issue by AugustCai** [ThreeMammals/Ocelot#771] opened 2019-01-29 03:47 UTC
## Expected Behavior
Because gateway requests will be timed out in more than 100 seconds, i want to set the timeout time so that requests do not report errors.

## Actual Behavior 
ReRoute Ocelot.Values.UpstreamPathTemplate specifies use QoS but no QosHandler found in DI container. Will use not use a QosHandler, please check your setup!

## Steps to Reproduce the Problem

  

1. Install Ocelot.Provider.Polly
2. to Startup#ConfigureServices the following: services.AddOcelot().AddPolly();
3. Add a section into ocelot.json
`"QoSOptions": {
    "TimeoutValue": 300000
  }`
4. Error occurred
` ReRoute Ocelot.Values.UpstreamPathTemplate specifies use QoS but no QosHandler found in DI container. Will use not use a QosHandler, please check your setup!`

## Specifications

  - Version: Ocelot v13.0.0, Ocelot.Provider.Polly v13.0.0
  - Platform: Windows 10 x64
  - Subsystem:

**Comment by eoware** [comment] 2020-02-11 20:17
If you want to just do timeouts, you can do this without having to do your own Ocelot fork/build or add Polly. 

Copy and paste the HttpClientBuilder and HttpClientHttpRequester classes from the Github branch you are using into your project and rename the classes (MyHttpClientBuilder and MyHttpClientHttpRequester, for example).

In HttpClientHttpRequester change this line to create your custom HttpClientBuilder:
var builder = new MyHttpClientBuilder(_factory, _cacheHandlers, _logger);

In your custom HttpClientBuilder, change the timeout to what you need:
_defaultTimeout = TimeSpan.FromSeconds(600);

In startup.cs, add this AFTER the call to 'AddOcelot':
services.RemoveAll<IHttpRequester>();

Then, somewhere after that, add:
services.TryAddSingleton<IHttpRequester, MyHttpClientHttpRequester>();

**Comment by raman-m** [comment] 2024-01-14 09:32
@AugustCai 
I didn't get your user scenario! 

Could you upgrade your version to v22 and confirm that the bug still exists please?

**Comment by raman-m** [comment] 2024-01-14 09:36
@ggnaegi I didn't get author's user case!
The author said about this line of code:
https://github.com/ThreeMammals/Ocelot/blob/bb795876c493af958f1d58c852ea56e94263906d/src/Ocelot/Requester/DelegatingHandlerHandlerFactory.cs#L74

**Comment by ggnaegi** [comment] 2024-01-14 22:22
@raman-m I would say so, we have reworked that part lately. Maybe it was a bug in version 13, maybe the user had to reference polly explicitely?

**Comment by raman-m** [comment] 2024-01-15 10:32
>@ggnaegi commented [on Jan 14](https://github.com/ThreeMammals/Ocelot/issues/771#issuecomment-1891090939)

Yes, we have to validate this bug: the author provided Steps to Repro.
But we have to perform validation for .NET 6+ and the latest v22 only (**develop** version too)

**Comment by ggnaegi** [comment] 2024-01-15 10:40
@raman-m Ok, maybe @ks1990cn would be willing to perform the validation for us?

**Comment by raman-m** [comment] 2024-06-15 12:43
@AugustCai  Any default timeout issues will be addressed by #2073

**Comment by raman-m** [comment] 2024-06-15 12:45
Duplicate of #2073

**Closed** 2024-06-15 12:45 UTC
Labels: bug, needs validation, needs feedback, QoS
