### ISSUE TITLE
WebSocket exception

### ISSUE THREAD

**Issue by zhaoyongjie183** [ThreeMammals/Ocelot#1683] opened 2023-07-28 07:26 UTC
Ocelot version: **19.0.2**

Ocelot configuration, a route：
```json
{
  "UpstreamPathTemplate": "/JavaMessageService/websocket/{url}",
  "UpstreamHttpMethod": [ "Get", "Post", "PUT", "DELETE", "OPTIONS" ],
  "DownstreamPathTemplate": "/api/websocket/{url}",
  "DownstreamScheme": "ws",
  "DownstreamHostAndPorts": [{
    "Host": "192.168.1.22",
    "Port": 9082
  }]
}
```

Direct Access to `ws://192.168.1.22:9082/api/websocket/xxl` was successful. 👇 
![image](https://github.com/ThreeMammals/Ocelot/assets/28800478/ec775226-606c-463a-8819-a9af83602271)

---

Ocelot UpstreamPathTemplate will report an error 👇 
![image](https://github.com/ThreeMammals/Ocelot/assets/28800478/a3c16774-51f3-4430-9e22-0539a8f5a9c4)

---

The error message of Ocelot pipeline is as follows:
```
System.ArgumentException: Only Uris starting with 'ws://' or 'wss://' are supported. (Parameter 'uri')
   at System.Net.WebSockets.ClientWebSocket.ConnectAsync(Uri uri, CancellationToken cancellationToken)
   at Ocelot.WebSockets.Middleware.WebSocketsProxyMiddleware.Proxy(HttpContext context, String serverEndpoint)
   at Ocelot.WebSockets.Middleware.WebSocketsProxyMiddleware.Invoke(HttpContext httpContext)
   at Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware.Invoke(HttpContext httpContext)
   at Ocelot.LoadBalancer.Middleware.LoadBalancingMiddleware.Invoke(HttpContext httpContext)
   at Ocelot.Request.Middleware.DownstreamRequestInitialiserMiddleware.Invoke(HttpContext httpContext)
   at Ocelot.Multiplexer.MultiplexingMiddleware.Invoke(HttpContext httpContext)
   at Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.Invoke(HttpContext httpContext)
```

**Comment by raman-m** [comment] 2023-07-28 15:35
Hi Zhao!
Thanks for your interest in Ocelot!

We have a big problem in Ocelot now because WebSockets feature is broken during releasing versions from v16 to v19.
.NET libs have changed much, a lot of changes.

```
System.ArgumentException: Only Uris starting with 'ws://' or 'wss://' are supported. (Parameter 'uri')
   at System.Net.WebSockets.ClientWebSocket.ConnectAsync(Uri uri, CancellationToken cancellationToken)
```
This exception is strange, because it says the URL is invalid.
Could you debug once again and make a screenshot, and show the real value of the `Uri uri` argument in runtime please?

---
> ocelot UpstreamPathTemplate will report an error

Didn't understand that!

---

We need to find a root cause of the issue...

**Comment by zhaoyongjie183** [comment] 2023-07-31 06:22
Hi raman!
This is my solution
![image](https://github.com/ThreeMammals/Ocelot/assets/28800478/79c545ba-cf1d-4a03-93d1-c4da38f9b901)
This is Nacos Config
![image](https://github.com/ThreeMammals/Ocelot/assets/28800478/1e4d3c65-258c-449b-ac6e-dbc0b94632aa)
This is the Gateway port
![image](https://github.com/ThreeMammals/Ocelot/assets/28800478/56b30219-3d1d-432c-9b95-f7d3e18f5972)
Direct Access to ws://192.168.1.22:9082/api/websocket/xxl was successful.    An error is reported when accessing through the Gateway address (ws://192.168.1.22:4000/JavaMessage Service/websocket/xxl).The entire operation process has been uploaded. From the video, it can be seen that there is an exception when ocelot forwards websockets. Forwarding the HTTP protocol is normal. From the logs in the video, it can be seen that forwarding the HTTP protocol address:/JavaMessageService/note/ureadCount was successful
![video](https://github.com/ThreeMammals/Ocelot/assets/28800478/ead0437d-9e89-47ed-a872-86a4bb77313e)

**Comment by zhaoyongjie183** [comment] 2023-08-02 01:06
Hi Raman!
Can you help me

**Comment by raman-m** [comment] 2023-08-03 12:14
> @zhaoyongjie183 commented [on July 31](#issuecomment-1657739688)

Nice pictures! But...

I cannot read non-English UI! 🤣 I don't understand Korean or China texts!

Your solution is completely custom because of custom Nacos service discovery setup.
What is the `Ocelot.Provider.Nacos` package? Can you share NuGet link?
Is this the repo of the provider: [GitHub | softlgl/Ocelot.Provider.Nacos](/softlgl/Ocelot.Provider.Nacos) ?
How does this service discovery provider constructs the URL to downstream services?
That's why I asked you to show me the `Uri uri` argument in runtime!!!
If the direct connection works it doesn't mean the URL constructed well by custom solution.

### Finally,
I can say that your video and configs won't help to find a root cause of the issue.

### Again,
Could you upload your Visual Studio solution to GitHub please, for evaluation?
Otherwise I cannot help you, sorry!
After cloning your solution repo and building the solution by VS compiler I will have a chance to debug the solution, and probably I/you/community will be lucky to find a root cause of the issue.

---

### Next steps
Returning to the protocol error: `CLOSED => 1006 CLOSE_ABNORMAL`
Did client (Ocelot) or downstream service close the protocol connection (generate the error)?

I'm asking you to analyze the logs of downstream service to understand why downstream server has closed the connection.

I assume we have Ocelot to Downstream server WebSocket libraries incompatibility. But we have to prove that!
What WebSocket lib/package is used on the downstream service side?
I am afraid we can communicate to .NET downstream service only, it is true if SignalR technology reused.
But for non-SignalR aka WebSocket communication we must match packs versions...
So, finally, I assume that we have **ws**-protocol versions incompatibility problem.

**Comment by zhaoyongjie183** [comment] 2023-08-07 02:42
Thank you very much for your patience. 
I've pulled the ocelot source code to local debug. Found the reason why the websocket connection is not working. 
The cause is that the upstream route template is defined repeatedly, causing the websocket to find the http protocol template

**Comment by raman-m** [comment] 2023-08-14 11:07
@zhaoyongjie183 commented [on Aug 7](#issuecomment-1667103635):
> **The cause is that the upstream route template is defined repeatedly**, causing the websocket to find the http protocol template

Sorry, does that mean you have invalid definitions of the routes in **ocelot.json**?
For example, if you have a duplicates of upstream templates (routes duplication) then you should have the following validation error in the logs: `$"{nameof(route)} {route.UpstreamPathTemplate} has duplicate")`.
If you have some another validation error, you should have in logs a message like that; `"Unable to start Ocelot, errors are: bla-bla-bla`.
**Could you confirm once again, that your issue is related to invalid configuration please?**
Can we close the issue?

**Comment by raman-m** [comment] 2023-09-19 16:45
@zhaoyongjie183
Good news! Your bug-issue will be resolved by linked PR.

The issue has been [accepted](#event-10413070866) due to open PR #1689 
- #1689

**Closed** 2023-09-29 08:27 UTC
Labels: bug, accepted, websockets

**Comment by raman-m** [comment] 2023-09-29 08:31
@zhaoyongjie183 Could you test & verify the bug fix plz? You just need to update develop branch of your forked repo.
