### ISSUE TITLE
Upgrade to 3.1 produces empty ocelot.json

### ISSUE THREAD

**Issue by mkanakis** [ThreeMammals/Ocelot#1247] opened 2020-05-27 13:51 UTC
## Expected Behavior

In .NET Core 2.2, inside the _Startup_ constructor we have the following configuration:

``` csharp
var builder = new ConfigurationBuilder().SetBasePath(env.ContentRootPath);

if (env.IsLocal())
{
  builder.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);
} else
{
   builder.AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: true);
}
builder.AddEnvironmentVariables();

 // Loads corresponding folder -> e.g. Products/Local/*.json
var gateway = System.Environment.GetEnvironmentVariable("ASPNETCORE_GATEWAY");
builder.AddOcelot($"/{gateway}/{env.EnvironmentName}/", env);

Configuration = builder.Build();
Environment = env;
```

In ConfigureServices we use the following line to add Ocelot as a middleware:

``` csharp
services.AddOcelot(Configuration);
```

As you can see, we specify a certain path for merging ocelot files for different environments.

After upgrading to .NET Core 3.1 the only difference is in _Configure_ method: 

``` csharp
app.UseRouting();

app.UseCors("CorsPolicy"); // to remove

app.UseAuthentication();

app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();
});

app.UseOcelot().Wait();
```

The above snippets should merge all ocelot.*.json files into ocelot.json and _work_ as intended. At least with 2.2 that was the case.

## Actual Behavior
In 3.1, the generated ocelot.json is empty! So every request leads to => **404**

One thing I noticed is in this line: 
``` csharp
builder.AddOcelot(string, env);
```

It used to get the ContentRootPath and add the rest {gateway}/{env.name}. 
Instead, it goes to "C:/" now. I fixed this by adding the ContentRootPath in front, but still the generated routing config is empty.

Produced ocelot.json:

``` json
{"Routes":[],"DynamicRoutes":[],"Aggregates":[],"GlobalConfiguration":{"RequestIdKey":null,"ServiceDiscoveryProvider":{"Scheme":null,"Host":null,"Port":0,"Type":null,"Token":null,"ConfigurationKey":null,"PollingInterval":0,"Namespace":null},"RateLimitOptions":{"ClientIdHeader":"ClientId","QuotaExceededMessage":null,"RateLimitCounterPrefix":"ocelot","DisableRateLimitHeaders":false,"HttpStatusCode":429},"QoSOptions":{"ExceptionsAllowedBeforeBreaking":0,"DurationOfBreak":0,"TimeoutValue":0},"BaseUrl":"http://localhost:56512","LoadBalancerOptions":{"Type":null,"Key":null,"Expiry":0},"DownstreamScheme":null,"HttpHandlerOptions":{"AllowAutoRedirect":false,"UseCookieContainer":false,"UseTracing":false,"UseProxy":true,"MaxConnectionsPerServer":2147483647},"DownstreamHttpVersion":null}}
```

## Specifications

  - Version: Ocelot 16.0.1
  - Platform: .NET Core 3.1

**Comment by mkanakis** [comment] 2020-05-27 14:18
Update: 

If I downgrade Ocelot to latest ***15*** version (v15.0.7), the configuration (ocelot.json) is back again, with **_.NET Core 3.1_**.

So narrowing down the problem, the empty configuration only occurs in:  **_v16.0.0 & v16.0.1_**

**Comment by Gluchito** [comment] 2020-05-28 06:49
Thank you for sharing, i spent a lot of time resolving this bug

**Comment by mkanakis** [comment] 2020-05-28 07:15
@Gluchito how did you fix it ? Or you didn't?

**Comment by amweiss** [comment] 2020-05-29 12:47
I've also found the 16 versions have an issue where it seems to break JWT authentication. Running 15.0.7 everything was fine. If I upgrade to 16.0.x and rename "ReRoutes" to "Routes" in the appsettings.json, the basic routes seem ok but when I inspect the Identity in the context it's not translating claims correctly. I don't have a simple case to post yet, but it seems like there's a step missing for the config upgrade or something is very broken.

**Comment by ediblecode** [comment] 2021-06-15 15:41
It looks like this is caused by this method:

https://github.com/ThreeMammals/Ocelot/blob/3ef6abd7465fc77632e4b2d5189fbbf47b457867/src/Ocelot/DependencyInjection/ConfigurationBuilderExtensions.cs#L37

And specifically by this line:

https://github.com/ThreeMammals/Ocelot/blob/3ef6abd7465fc77632e4b2d5189fbbf47b457867/src/Ocelot/DependencyInjection/ConfigurationBuilderExtensions.cs#L78

I followed the [config from this answer](https://github.com/ThreeMammals/Ocelot/issues/1047#issuecomment-548166528) for .NET Core 3.1. But did the following instead:

```diff
-config.AddOcelot("your folder", hostingContext.HostingEnvironment);
+config.AddJsonFile($"ocelot/ocelot.{hostingContext.HostingEnvironment.EnvironmentName}.json", true, true);
```

So avoiding the call to `AddOcelot` avoids the _ocelot.json_ file being overwritten.

**Comment by raman-m** [comment] 2023-09-21 19:26
@mkanakis Hi Marios!
Thanks for your interest in Ocelot!

I see you fought with Ocelot config files for different environments.
I believe linked PR 1569 will help you much.

**Closed** 2023-09-23 13:49 UTC
Labels: bug, proposal

**Comment by raman-m** [comment] 2023-09-23 14:02
@mkanakis 
> In .NET Core 2.2, inside the _Startup_ constructor we have the following configuration:

> ## Specifications
>  - Version: Ocelot **16.0.1**
>  - Platform: **.NET Core 3.1**

We don't support .NET Core 3.x since [16.0.2](../releases/tag/16.0.2) release.
Current version is .NET 7 with Ocelot [19.0.x](../releases) releases.

If the issue still persists, please open new issue/PRs.
