### ISSUE TITLE
Doesn't reload config file in k8s

### ISSUE THREAD

**Issue by Marusyk** [ThreeMammals/Ocelot#684] opened 2018-11-12 23:30 UTC
I'm using k8s to deploy image with Ocelot. I need to change route configs without restart Ocelot. So, from docs I found that:
```csharp
.AddJsonFile(Path.Combine("configurations", "ocelot.json"), true, true)
```
should work, but it doesn't.

## Steps to Reproduce the Problem

  1. Program.cs
```csharp
private static IWebHostBuilder CreateWebHostBuilder(string[] args)
{
	return WebHost.CreateDefaultBuilder(args)
		.ConfigureAppConfiguration((hostingContext, config) =>
		{
			config
				.SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)
				.AddJsonFile("appsettings.json", true, true)
				.AddJsonFile(Path.Combine("configurations", "ocelot.json"), true, true)
				.AddEnvironmentVariables();
		})
		.UseStartup<Startup>();
}
```
  2. Create ConfigMap
```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ocelot-api
  labels:
    module: ocelot
    app: api
data:
  ocelot: '{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "users-api",
          "Port": 7511
        }
      ],
      "UpstreamPathTemplate": "/users/{everything}"
    }
  ]
}'
```
  3. A part of my Deployment

```yml
spec:
  containers:
  - name: master
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
    image: apigateway-ocelot
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config
       mountPath: /app/configurations
  volumes:
  - name: config
     configMap:
       name: ocelot-api
       items:
       - key: ocelot
         path: ocelot.json 
```
  4. Run. Everything works. But now I need to change a route in configMap and apply
```json
"UpstreamPathTemplate": "/usersnew/{everything}"
```
5. The mounted file is changed. But Ocelot returns 404 and old route works.

## Specifications

  - Version: 11.0.2
  - Platform: docker
  - Subsystem: k8s

**Comment by Marusyk** [comment] 2018-11-24 20:44
any suggestions?

**Comment by briansantura** [comment] 2018-12-11 07:08
@Marusyk Simply adding reloadOnChange: true won't actually update the configuration unless you add the property to the IoC container.

Every configuration file specified gets loaded into IConfigurationRoot. You can do this in order to see the changes made to the configuration file in runtime.

services.AddSingleton(_ => Configuration);

Does this answer your question?

**Comment by briansantura** [comment] 2018-12-11 07:14
Please also see https://github.com/ThreeMammals/Ocelot/issues/663

**Comment by Marusyk** [comment] 2018-12-11 22:46
@briansantura Thanks but it still not working when I change ConfigMap 😕

**Comment by Marusyk** [comment] 2018-12-16 23:52
what does it mean?

**Comment by sharpn** [comment] 2019-01-04 20:30
In kubernetes a change to a config map isn't seen by any running pods until they are restarted, therefore updating it wont take effect until ocelot is restarted

**Comment by sharpn** [comment] 2019-01-10 09:55
seen the note about subpaths here https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap#mounted-configmaps-are-updated-automatically

**Comment by philproctor** [comment] 2019-01-10 14:04
Thanks for the info @sharpn I will close this issue now.

**Closed by philproctor** 2019-01-10 14:04 UTC
Labels: bug, needs validation

**Comment by rzonta** [comment] 2021-02-11 20:16
This is related to a problem in how dotnet detect file changes, as seen here: https://github.com/dotnet/runtime/issues/36091
Until the problem is fixed you can use a workaround like this: https://github.com/fbeltrao/ConfigMapFileProvider
