### ISSUE TITLE
Upstream SSL Certificate

### ISSUE THREAD

**Issue by kurtisane** [ThreeMammals/Ocelot#1669] opened 2023-06-15 09:04 UTC
Hi,
I'm not able to find anything in the docs to be honest. We have a typical microservice architecture backend application with Ocelot being our API gateway. We would like to keep the downstream connections in http and just the upstream connection to the clients being forced to use https. 

I sadly have no clue where do configure this and I have no clue where to put the certificate. We are deploying using docker/docker-compose. 

Any suggestions or directions towards some documentation would be greatly appriated !

**Comment by raman-m** [comment] 2023-06-15 10:26
Ocelot team is not a consultancy firm which provides services in industry of web application hosting!
But... for a quick reply...
In your user scenario, Upstream problem, gateway app hosting problem.
Why do you deploy your gateway app to Docker container? For what reason or goal?

If you would like to have some scalability for the gateway, I would recommend to deploy gateway app to any cloud service like Azure, AWS. Those cloud services have excellent scalability, horizontal and vertical.

I don't recommend to use Docker for localhost development if you have no experience with Docker services.
If you are going to create development environment in clouds using ECR/ECS or ACR/AKS that is a bit complicated scenario.
I would recommend to create Kubernetes/Docker ecosystem for Staging and Production environments only. 

Concerning SSL certificate....
If you use clouds like Azure, AWS and GCP there are no problems with certificates because all instances of services are deployed with signed-certificates by root-certificates of Microsoft, Amazon and Google.

If you don't use any clouds and has custom hosting endpoint (web server for example) you have to ask/buy certificates from your hosting provider.
In case of deployment your gateway to a Docker image/container you have to create SSL certificate and install this certificate private keys at operating system inside of docker image. You need to browse some webpages with instructions on Internet how to manage SSL-certificate for concrete OS. Just ask your hosting provider administrator and you will get all answers.

Here are some testing and development tips related to SSL exactly for Ocelot core.
More about creation of self-signed certificates and Ocelot deployment you can find in docs: 
- [Create SSL Cert for Testing](https://ocelot.readthedocs.io/en/latest/building/tests.html?highlight=self-signed#create-ssl-cert-for-testing)
- [SSL Errors](https://ocelot.readthedocs.io/en/latest/features/configuration.html#ssl-errors)

Hope it helps!

**Comment by raman-m** [comment] 2023-06-15 10:39
The guy from #1667 has the same SSL problem but with Downstream service 🤣  
There is no matter if it's downstream or upstream SSL problem.
The problem is wrong usage of SSL certificates. Self-signed certificates are the most complicated scenario of web apps deployment.
There is no much sense to lose the time with self-signed certificates in development environment! Just use **http**-protocol for development!

**Comment by raman-m** [comment] 2023-06-15 10:44
@kurtisane ! So strange user name )) What's your name?

Let's find some workaround within one week please!
Your issue will be accepted or declined until June 23.
---

**Comment by kurtisane** [comment] 2023-06-20 07:58
1. Thanks for your time and efforts !
2. We have a on-prem application. We are installing our backend locally in networks of our customers. 
3. For development we are using http. It's just for on-prem deployments.

**Comment by raman-m** [comment] 2023-06-20 14:03
Well... Good! But I still cannot understand your user scenario, and how is it related to Ocelot...

Did [my tips](#issuecomment-1592780702) help you solve your SSL certificate issue?
Can we close this issue?

**Comment by kurtisane** [comment] 2023-06-20 20:45
We would like to configure ocelot to use the self signed certificate for the upstream connections. 

There is no documentation on how to do that.

**Comment by raman-m** [comment] 2023-06-21 19:36
Cannot you google?
Here is a great manual about self-signed certificates for ASP.NET web apps:
- [Generate Self-Signed Certificates Overview - .NET | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/core/additional-tools/self-signed-certificates-guide)

Once again, you try to use **https** scheme for gateway web app deployment for your localhost development.
You just lose your time because in development environment it is totally fine to use **http** scheme!
And if you have deployed your gateway solution to some cloud hosting (Azure, AWS) you will have certificates of hosting provider. So, you use certificates out of the cloud box! That's it!
If you try to deploy gateway web app to a Docker container then you need to use native tools of each operating system.
I believe [the manual](https://learn.microsoft.com/en-us/dotnet/core/additional-tools/self-signed-certificates-guide) above covers this Docker case.
But again, I suggest you to deploy your Docker image to Azure/AWS to reuse native certificates of cloud providers!!!!!!! Make your cloud endpoint public, and you will be able to communicate to this gateway instance without problems, without any self-signed certs!!!

> There is no documentation on how to do that.

Of course! Because SSL certificate installation is out of Ocelot responsibility. It is a question of web app deployment!
But, if you are nuts cracker and wish to use self-signed certificates for Docker deployment, just take a few days of your time and use this manual: [Generate Self-Signed Certificates Overview - .NET | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/core/additional-tools/self-signed-certificates-guide)

Good luck!

**Closed** 2023-06-26 16:05 UTC
Labels: invalid, wontfix
