### ISSUE TITLE
support SignalR

### ISSUE THREAD

**Issue by cristianiorga** [ThreeMammals/Ocelot#344] opened 2018-05-04 14:32 UTC
## Expected Behavior / New Feature
SignalR websockets can be successfully rerouted with Ocelot

## Actual Behavior / Motivation for New Feature
Fails on the handshake due to inability to map websockets and xhr requests for the same upstream url

## Steps to Reproduce the Problem

  1. Clone https://github.com/cristianiorga/OcelotSignalRTest
  2. Start DummySignalR
  3. Start APIGatewayTest

  4. Start DummySignalRClient
Expected: logs dummy test message to console
Actual: cannot enstablish connection

  5. Open DummySignalRWebClient.html in browser
Expected: logs dummy test message to browser console
Actual: cannot establish connection

Browser network log:
![error](https://user-images.githubusercontent.com/9863741/39633315-e3a019ee-4fb7-11e8-8594-397fad1c1b90.PNG)

Detailed error:
![detailed error](https://user-images.githubusercontent.com/9863741/39633321-ecf08916-4fb7-11e8-95b8-c9e019ed9455.PNG)

How a successfull handshake looks like:
![signalr handshake](https://user-images.githubusercontent.com/9863741/39633303-da0cb20c-4fb7-11e8-88ee-a962dccc6362.PNG)

## Specifications

  - Version: 6.0.0
  - Platform: Windows
  - Subsystem: Windows 10 Enterprise 64 bit

Notes:
In order to have a successful handshake with SignalR not only the websocket has to be rerouted.

**Comment by cristianiorga** [comment] 2018-05-05 15:36
@TomPallister SignalR will be part of the .NET Core 2.1 release coming **mid-2018**. You can read more about that at https://blogs.msdn.microsoft.com/webdev/2018/02/02/asp-net-core-2-1-roadmap/ , https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-0-preview1-getting-started-with-signalr/ and https://github.com/aspnet/SignalR/milestones
Currently there is a .NET Core 2.1 Developer preview for SignalR and is that one I used in this issue. 

I believe that this would be a great feature for Ocelot and I would be willing to help if you can plan and coordinate the work.

**Comment by ogomaemmanuel** [comment] 2018-05-13 16:35
I am building a mobile app using Ionic, when I test it on mobile  signalR and ocelot work perfectly, the only problem i have is when testing on the browser. It brings an error i believe could be as result of cors but i can't solve it. here is the error 

Failed to load resource: the server responded with a status of 405 (Method Not Allowed)
?ionicplatform=android&http://localhost:8100/ionic-lab&http://localhost:8100/ionic-lab&http://localhost:8100/ionic-lab#/products:1 Failed to load http://myIp/NotificationHub/negotiate: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 405.

**Comment by ogomaemmanuel** [comment] 2018-05-13 16:36
my configuration is as follows
{
      "DownstreamPathTemplate": "/NotificationHub/negotiate",
      "UpstreamPathTemplate": "/NotificationHub/negotiate",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "servicename",
          "Port": 80
        }
      ],
      "UpstreamHttpMethod": ["Options", "Post" ]
    },

    {
      "DownstreamPathTemplate": "/NotificationHub",
      "UpstreamPathTemplate": "/NotificationHub",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "servicename",
          "Port": 80
        }
      ],
      "UpstreamHttpMethod": [ "Options", "Get", "Post" ]

    },

**Comment by ogomaemmanuel** [comment] 2018-05-13 16:39
public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors(options =>
            {
                options.AddPolicy("CorsPolicy",
                    builder => builder
                    .WithOrigins("http://localhost:8100")
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .AllowCredentials()
                    );
            });
            services.AddMvc();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseCors("CorsPolicy");
            app.UseMvc();
        }

**Comment by TomPallister** [comment] 2018-05-14 17:37
@ogomaemmanuel it is probably the same problem as @cristianiorga mentioned to open this ticket. I have not had time to look into the issue yet I'm afraid. I cannot give a time frame either. Maybe I will have time in the next few months. If you want to help out I would suggest forking the Ocelot repository and debugging the code to see whats going on. I'm more than happy to accept PRs and give advice.

**Comment by IvanMeng** [comment] 2018-05-16 08:31
@cristianiorga APIGatewayTest project will be changed.
  ocelot.json  
`{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/dummy",
      "DownstreamScheme": "ws",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 50000
        }
      ],
      "UpstreamPathTemplate": "/api/dummy"
    },
    {
      "DownstreamPathTemplate": "/dummy/negotiate",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 50000
        }
      ],
      "UpstreamPathTemplate": "/api/dummy/negotiate"
    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "http://localhost",
    "AdministrationPath": "/administration",
    "RequestIdKey": "OcRequestId"
  }
}  `

and Program.cs 
`.Configure(app =>
            {
                app.UseWebSockets();
                app.UseOcelot().Wait();
            })`
you can try. I get the same result as DummySignalR

**Comment by TomPallister** [comment] 2018-08-02 17:18
from #524 

Expected Behavior / New Feature
We are using ocelot with the feature websockets. We are using Signalr Core and trying to forward it to the correct server. With that we are using headers on the requests.

The headers disappear once it goes through ocelot. Is this on purpose?
We verified that the headers will be send to the signalr server when it doen't use ocelot.

Config:

"ReRoutes": [{
      "DownstreamPathTemplate": "/{catchAll}",
      "DownstreamScheme": "ws",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5000
        }
      ],
      "UpstreamPathTemplate": "/gateway/{catchAll}",
      "UpstreamHttpMethod": [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ]
    }]
Actual Behavior / Motivation for New Feature
The headers are being forwarded with the websockets

Steps to Reproduce the Problem
Start a signalr core server
Configure ocelot as described in http://ocelot.readthedocs.io/en/latest/features/websockets.html
Connect a client throuh ocelot and send a header with it.
Check the headers received on the server
Specifications
Version: 8.0.2
Platform: Windows 10
Subsystem: Microsoft.AspNetCore.SignalR.Client 1.0.1

**Comment by JanKolk** [comment] 2018-08-03 07:53
I created a pull request to add headers to the request.

With the following templates it works:

Target framework: 2.1.2
Microsoft.AspNetCore.SignalR.Client 1.0.2
Ocelot develop with my pull-request

```
 public class Program
    {
        public static void Main(string[] args)
        {
            var webHost = WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseIISIntegration()
                .Build();

            webHost.Run();
        }
    }

    public class Startup : IStartup
    {
        public IConfiguration Configuration { get; }

        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("ocelot.json")
                .AddEnvironmentVariables();

            Configuration = builder.Build();
        }

        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddOcelot(Configuration);
            return services.BuildServiceProvider();
        }

        public void Configure(IApplicationBuilder app)
        {
            app.UseWebSockets();
            app.UseOcelot().Wait();
        }
    }
```

ocelot.json
```
{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/{catchAll}",
      "DownstreamScheme": "ws",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 50000
        }
      ],
      "UpstreamPathTemplate": "/gateway/{catchAll}",
      "UpstreamHttpMethod": [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ]
    }
 ]
}

```

**Comment by TomPallister** [comment] 2018-08-04 08:01
Just released in 8.0.7

**Closed by TomPallister** 2018-08-04 08:01 UTC
Labels: enhancement, help wanted, large effort, merged

**Comment by souchprod** [comment] 2019-11-02 23:42
Hi, sorry to ask as it may be a stupid question but i don't really get how it fix the original issue **"Fails on the handshake due to inability to map websockets and xhr requests for the same upstream url"**.
For the http(s) negociate part, should be still add an http(s) DownstreamScheme plus a ws DownstreamScheme for the same route ?

**Comment by DeminAO** [comment] 2020-09-04 08:37
![image](https://user-images.githubusercontent.com/57270583/92219125-d0001380-eea2-11ea-9ca8-25fa8d67c255.png)

hi, there's no typo here?

**Comment by jsuag** [comment] 2021-05-17 00:04
Hi, It works fine for me, but when I try to balance the SignalR API, the connection doesn't work, it returns 404 error. This is my configuration:
{
  "DownstreamPathTemplate": "/Hubs/{everything}",
  "DownstreamScheme": "ws",
  "ServiceName": "OrderApi",
  "UpstreamPathTemplate": "/Hubs/{everything}",
  "LoadBalancerOptions": {
    "Type": "CookieStickySessions",
    "Key": "ASP.NET_SessionId",
    "Expiry": 1800000
  },
  "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete", "Options" ],
  "QoSOptions": {
    "TimeoutValue": 120000
  }
},

The requests have been resolved by different instances of the API:

info: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
      requestId: 0HM8OONQSHKOU:00000007, previousRequestId: no previous request id, message: /Hubs/{everything} route does not require user to be authorised
info: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HM8OONQSHKOU:00000007, previousRequestId: no previous request id, message: 200 (OK) status code, request uri: ws://localhost:5000/Hubs/OrderHub/negotiate?negotiateVersion=1
info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      requestId: 0HM8OONQSHKOU:00000008, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /Hubs/{everything}
info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HM8OONQSHKOU:00000008, previousRequestId: no previous request id, message: No authentication needed for /Hubs/OrderHub
info: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
      requestId: 0HM8OONQSHKOU:00000008, previousRequestId: no previous request id, message: /Hubs/{everything} route does not require user to be authorised
warn: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HM8OONQSHKOU:00000008, previousRequestId: no previous request id, message: 404 (Not Found) status code, request uri: ws://localhost:5080/Hubs/OrderHub?id=6FDYdEFYgnV3lQ_xluR9ZA&_=1621209543544
