### ISSUE TITLE
In C#, when using Ocelot, the ContentLength is 0 when forwarding data to downstream services.

### ISSUE THREAD

**Issue by Tell969696** [ThreeMammals/Ocelot#2077] opened 2024-05-29 02:41 UTC
## Expected Behavior / New Feature
Using Ocelot version 18.0, in an ABP framework environment, the content length of front-end access is normal when using `app.Use`. However, when inspecting the information forwarded by Ocelot in a `DelegatingHandler`, the content length is 0.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by raman-m** [comment] 2024-05-29 08:43
Use `POST` verb to forward body successfully.
But I believe it is possible with `GET` too.
There is problem with multiplexing aka [Request Aggregation](https://ocelot.readthedocs.io/en/latest/features/requestaggregation.html) feature where we have the problem with forwarding body. But the problem is already addressed in PR #2050 and merged as commit https://github.com/ThreeMammals/Ocelot/commit/233f87a43f5e2fbb1857f17bb6181fbd05de03bc.
So, our recommendation is migration to version 23.3 which will be released in a week.

> Using Ocelot version 18.0

This is outdated version! Migrate to latest version [23.2.2](https://www.nuget.org/packages/Ocelot/23.2.2) please!

### P.S.
If you have custom overrides of the default Ocelot implementations then we are not responsible for the stability.
Overrides such as: custom delegating handlers, custom middlewares, custom replaces services in DI.
So, we can't help you!

**Closed by raman-m** 2024-05-29 08:43 UTC
