### ISSUE TITLE
Request Body Not Considered in Ocelot Cache Key Calculation

### ISSUE THREAD

**Issue by mertgundoganx** [ThreeMammals/Ocelot#2087] opened 2024-06-04 19:35 UTC
I am using Ocelot in my .NET project and have recently implemented a new caching mechanism. However, I have encountered an issue where Ocelot is using the same cache key for different requests even though the request bodies are different. As a result, different requests are returning the same response.

## Specifications

  - Version: 23.2.2 on .NET 6

**Comment by raman-m** [comment] 2024-06-05 10:22
Hello, Mert!
It's great to know that you've incorporated Ocelot into your products!

As for the caching issue...

> I am using Ocelot in my .NET project and **have recently implemented a new caching mechanism**. 

Please note that we cannot be held accountable for hybrid solutions if modifications have been made to Ocelot services.


> I have encountered an issue where Ocelot is using the same cache key for different requests **even though the request bodies are different**.

It's important to note that the cache key is generated based on the route definition, which includes paths, service names, HTTP verbs, etc. For a more effective analysis, could you please provide your `ocelot.json` file? Regarding the cache versus load balancing keys, we have addressed this in the past with:
- PR #1944
- A commit in the develop branch: https://github.com/ThreeMammals/Ocelot/commit/8845d1b98d2c3b0bd633ebd2b526b923687edd33

The aforementioned fix was included in the release of version 23.1.0, which you can find here: [23.1.0](https://github.com/ThreeMammals/Ocelot/releases/tag/23.1.0)

---
Regarding body hashing for cache keys, we have implemented a fix:
- PR #2058
- Commit: https://github.com/ThreeMammals/Ocelot/commit/6e9a975fae3b26229c3f0b3c1a475a7b05e95fee

This fix will be included in the upcoming release, version 23.3, which is scheduled for release in a few days. Please look out for the new version!
If you require the bug fix urgently, you may fork the repository and compile the DLL manually in Visual Studio.

**Is there anything else I can assist with?**

**Comment by mertgundoganx** [comment] 2024-06-08 19:18
> Regarding body hashing for cache keys, we have implemented a fix:
> 
> * PR [#2054 #2059 Manage `EnableContentHashing` setting by global `CacheOptions` #2058](https://github.com/ThreeMammals/Ocelot/pull/2058)
> * Commit: [6e9a975](https://github.com/ThreeMammals/Ocelot/commit/6e9a975fae3b26229c3f0b3c1a475a7b05e95fee)
> 
> This fix will be included in the upcoming release, version [23.3](https://github.com/ThreeMammals/Ocelot/releases/tag/23.3.0), which is scheduled for release in a few days. Please look out for the new version! If you require the bug fix urgently, you may fork the repository and compile the DLL manually in Visual Studio.
> 
> **Is there anything else I can assist with?**

Thank you for your answer. I'm impatiently waiting for the new version

**Comment by raman-m** [comment] 2024-06-09 10:59
### Issue #2058 is now available in the [23.3.0](https://github.com/ThreeMammals/Ocelot/releases/tag/23.3.0) pre-release!
The [Ocelot 23.3.0 package](https://www.nuget.org/packages/Ocelot/23.3.0) can be downloaded from NuGet for `dotnet restore` right today. The official 23.3 release is expected to be finalized within a few days, likely by Monday.
This issue will be closed accordingly...

**Comment by raman-m** [comment] 2024-06-11 14:29
Duplicate of #2059

**Comment by raman-m** [comment] 2024-06-11 14:37
Already fixed by #2058 
Delivered as a part of release: [23.3.0](https://github.com/ThreeMammals/Ocelot/releases/tag/23.3.0)
Commit &rarr; https://github.com/ThreeMammals/Ocelot/commit/6e9a975fae3b26229c3f0b3c1a475a7b05e95fee
NuGet package with the fix: [Ocelot.23.3.0](https://www.nuget.org/packages/Ocelot/23.3.0)

**Closed by raman-m** 2024-06-11 14:37 UTC
Labels: bug, Caching, Spring'24

**Comment by raman-m** [comment] 2024-06-11 14:40
@mertgundoganx
Please, upgrade to v23.3.0+
Docs: [EnableContentHashing option](https://ocelot.readthedocs.io/en/23.3.3/features/caching.html#enablecontenthashing-option)

**Comment by mertgundoganx** [comment] 2024-06-12 19:05
> @mertgundoganx Please, upgrade to v23.3.0+ Docs: [EnableContentHashing option](https://ocelot.readthedocs.io/en/23.3.3/features/caching.html#enablecontenthashing-option)

I upgraded version and made the changes immediately. It happened the way I wanted. Thanks again
