### ISSUE TITLE
Whether the configuration file cannot be mounted? (docker)

### ISSUE THREAD

**Issue by KarlHuang0509** [ThreeMammals/Ocelot#386] opened 2018-06-07 02:29 UTC
## Expected Behavior / New Feature
I deploy the site with docker, and I want to mount the ocelot.Development.json configuration file,
but there was an error running the site.
if don't mount the ocelot.Development.json configuration file, the website works well.

## Steps to Reproduce the Problem
1. Ocelot Program.cs 、Startup.cs code
Program.cs 
public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((webhost, builder) =>
                {
                    builder.SetBasePath(webhost.HostingEnvironment.ContentRootPath)
                    .AddJsonFile("ocelot.json", optional: true, reloadOnChange: true)
                    .AddJsonFile($"ocelot.{webhost.HostingEnvironment.EnvironmentName}.json", optional: true, reloadOnChange: true)//
                    .AddCommandLine(args)
                    .AddEnvironmentVariables();
                })
                .UseStartup<Startup>()
                .Build();

Startup.cs
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseOcelot().Wait();
        }

2. Generate a docker image of the site

Dockerfile 

FROM microsoft/aspnetcore:2 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2 AS build
WORKDIR /code
COPY . .
RUN dotnet restore
RUN dotnet build -c Release -o /app

FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "OcelotGateway.dll"]

3. Run the app
docker run -d -p 5002:80 -e ASPNETCORE_ENVIRONMENT=Development -v /home/ocelotgateway/config/ocelot.Development.json:/app/ocelot.Development.json --name oce ocelotgateway:1.0.0

4.docker logs oce 
Unhandled Exception: System.AggregateException: One or more errors occurred. (Device or resource busy) ---> System.IO.IOException: Device or resource busy
   at System.IO.UnixFileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Ocelot.Configuration.Repository.DiskFileConfigurationRepository.Set(FileConfiguration fileConfiguration)
   at Ocelot.Configuration.Setter.FileAndInternalConfigurationSetter.<Set>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.<SetFileConfig>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.<CreateConfiguration>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.<UseOcelot>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.<UseOcelot>d__0.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at OcelotGateway.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /code/OcelotGateway/Startup.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at OcelotGateway.Program.Main(String[] args) in /code/Program.cs:line 18

public Task<Response> Set(FileConfiguration fileConfiguration)
        {
            string jsonConfiguration = JsonConvert.SerializeObject(fileConfiguration, Formatting.Indented);

            lock(_lock)
            {
                if (System.IO.File.Exists(_configFilePath))
                {
                    System.IO.File.Delete(_configFilePath);
                }

                System.IO.File.WriteAllText(_configFilePath, jsonConfiguration);
            }

            return Task.FromResult<Response>(new OkResponse());
        }

Whether the configuration file cannot be mounted?
Why delete the configuration file?

## Specifications

  - Version:7.0.4
  - Platform:linux
  - Subsystem:centos7

**Comment by TomPallister** [comment] 2018-06-08 14:46
@KarlHuang0509 thanks for your interest in the project. The configuration file is being used by something when Ocelot starts up. There is an issue open to not delete the file. Ocelot deletes the file because this used to make sense before certain changes were made.

**Comment by TomPallister** [comment] 2018-06-08 14:55
issue is #373.

**Comment by TomPallister** [comment] 2018-06-13 18:36
closing as duplicate of #373

**Closed by TomPallister** 2018-06-13 18:36 UTC

**Comment by KarlHuang0509** [comment] 2018-06-14 07:51
@TomPallister  ok. thanks.
