### ISSUE TITLE
route by headers

### ISSUE THREAD

**Issue by wangfengjun404** [ThreeMammals/Ocelot#1373] opened 2020-11-13 15:34 UTC
## like this:
```json
{
headers:{
"custom_header":"some value",
"another_header":"other value"
}
}
```

**Comment by CorporateActionMan** [comment] 2022-04-01 07:22
I would like to plus one this .. I'll take a fork to see what the the art of the possible is

**Comment by raman-m** [comment] 2024-03-26 15:01
Duplicate of #360

**Comment by raman-m** [comment] 2024-03-26 15:02
And we have open PR #1312

**Closed by raman-m** 2024-03-26 15:02 UTC
