### ISSUE TITLE
Question about Ocelot and Consul

### ISSUE THREAD

**Issue by cinqart1** [ThreeMammals/Ocelot#983] opened 2019-08-07 12:57 UTC
Hello! I´m using ocelot with consul service discovery, but I dont know how to configure ocelot to not request a service in consul that have two instance, but one of them is down.
In consul I have created a check to verify any instance and one of them is down...but ocelot continue to send request in LoadBalance mode to that service instance!
Someone could help me?
Coul be a link or a explanation...´cause I dont know if there are problem with ocelot or consul or a bad configuration!

Tnks

**Comment by raman-m** [comment] 2024-03-16 15:34
Duplicate of #1041

**Comment by raman-m** [comment] 2024-03-16 15:40
Hi @cinqart1 !
Your issue is the same as #1041. But this issue has no open PR to fix it.

How did you solve the problem?
Unfortunately Ocelot has no Health Check feature to monitor all route downstream services.
But Consul has native health checks feature: [Define health checks](https://developer.hashicorp.com/consul/docs/services/usage/checks) 
And it would be a dilemma which feature to use: Consul native or Ocelot's one?
As a team, we will discuss this situation.

@ggnaegi FYI

**Comment by raman-m** [comment] 2024-06-15 12:17
Will be fixed by #1041

**Closed by raman-m** 2024-06-15 12:17 UTC
Labels: Load Balancer, Consul, Health Check
