### ISSUE TITLE
Getting 502 Bad Gateway

### ISSUE THREAD

**Issue by pmjaleel** [ThreeMammals/Ocelot#1206] opened 2020-04-20 07:18 UTC
I have deployed the API-Gateway in Azure APP service. This was done after test this gateway in local environment.

Once we try to access the swagger page or the URL of the API-Gateway, we are getting 502 bad gateway.

Is there something that we would have missed. The Ocelot version that we are using is 14.1

**Comment by vchy1997** [comment] 2020-04-25 06:26
hi
I also triggered this problem, but eventually found that it was caused by a configuration problem. The port used for the local host test is port 80, but I did not notice that the azure application is https protocol, so I configured the port to 443 to solve the problem perfectly. Hope it helps you

**Comment by Crennotech** [comment] 2020-12-05 22:09
Thanks vchy1997. I had the same issue, spent whole day till I found this. Ocelot documentation  should have an example config file for local and production servers.

**Comment by AJCADamen** [comment] 2021-03-12 15:35
I still have the error when using port 443

**Comment by raman-m** [comment] 2024-03-23 16:53
@pmjaleel
Sad to hear such bad news! )))
But pay your attention that currently we don't support Azure and [Swagger](https://ocelot.readthedocs.io/en/latest/introduction/notsupported.html#swagger)!

I could assume only that you had Azure service misconfiguration issue.
I don't see anything here which can be fixed by Ocelot team.

**Comment by raman-m** [comment] 2024-03-23 16:53
**Azure service misconfiguration issue!**

**Closed by raman-m** 2024-03-23 16:53 UTC
