### ISSUE TITLE
Limit current for a single ip,

### ISSUE THREAD

**Issue by tkggusraqk** [ThreeMammals/Ocelot#1202] opened 2020-04-16 12:25 UTC
Limit the amount of one ip access over a period of time, is this solution https://github.com/ThreeMammals/Ocelot/issues/1050?

**Comment by tkggusraqk** [comment] 2020-04-17 01:35
@binarymash

**Comment by raman-m** [comment] 2024-03-23 16:27
@tkggusraqk
Yes, we will try to implement this in #1050. I've reopened #1050 just today.

Any your contribution is welcome!

**Comment by raman-m** [comment] 2024-03-23 16:28
As a temp solution you could try to use :point_down:  
- [Future and ASP.NET Core Implementation](https://ocelot.readthedocs.io/en/latest/features/ratelimiting.html#future-and-asp-net-core-implementation)

**Comment by raman-m** [comment] 2024-03-23 16:29
Duplicate of #1050

**Closed by raman-m** 2024-03-23 16:29 UTC
Labels: Rate Limiting
