### ISSUE TITLE
Routing based on value in claim

### ISSUE THREAD

**Issue by twilly86** [ThreeMammals/Ocelot#564] opened 2018-08-20 14:25 UTC
## Expected Behavior / New Feature

I'm looking for direction on how to route to a specific downtream resource based on a value in .net identity claim.  Ex) user has claim    TenantId = "xxx" and this would route them to a specic downstream resource I have setup.

## Actual Behavior / Motivation for New Feature

Need to support multi tenant multi site routing with single enpoint visible to user

## Steps to Reproduce the Problem

  1. Go to example.com
  1. User would login and get a claim "TenantId": "xxx"
  1. Route is setup to check for "TenantId" claim and route to specific resource based on TenantId value

**Comment by TomPallister** [comment] 2018-08-20 19:17
@twilly86 thanks for your interest in Ocelot, this isn't possible at the moment. There are some issues open for different ways of doing routing that I intend to look at after doing some refactoring to make Ocelot better. I will take a look at this when I get round to them...it isn't something I will be able to do super quick. This will be a big change to Ocelot because the routing happens before authentication at the moment.

**Comment by TomPallister** [comment] 2018-09-19 06:40
Turns out this is a duplicate of #460

**Closed by TomPallister** 2018-09-19 06:40 UTC
Labels: enhancement, help wanted, large effort
