### ISSUE TITLE
Ocelot WebSocketsProxyMiddleware does not handle 401 Authentication error and returns 500 Internal Server Error

### ISSUE THREAD

**Issue by Julandia** [ThreeMammals/Ocelot#1360] opened 2020-10-26 18:42 UTC
Our company plans to use Ocelot as API gateway for the company intranet services. We had below authentication problem when routing the SignalR requests using Ocelot. Is this a defect of Ocelot or do I miss some configuration?

## Expected Behavior / New Feature
I expect that when server side returns 401 authentication, Ocelot should return the error to upstream

## Actual Behavior / Motivation for New Feature
Ocelot return 500 Internal Server Error

## Steps to Reproduce the Problem

  1. Have SignalR client and service running. Both service and client use .NetFramework SignalR. The service uses .Net Framework Web API stack and implement authentication middleware. 
  2. Client sends a SignalR request to the service via Ocelot.
  3. Ocelot does not handle 401 authentication error returned by service and throws 500 Internal Server Error during SignalR connection: 

Error stack:
Exception has occurred: CLR/System.Net.WebSockets.WebSocketException
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll: 'The server returned status code '401' when status code '101' was expected.'
   at System.Net.WebSockets.WebSocketHandle.<ConnectAsyncCore>d__24.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ClientWebSocket.<ConnectAsyncCore>d__16.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.WebSockets.Middleware.WebSocketsProxyMiddleware.<Proxy>d__7.MoveNext() in C:\simhub\Ocelot\src\Ocelot\WebSockets\Middleware\WebSocketsProxyMiddleware.cs:line 118

## Specifications

  - Version: 16.0.1
  - Platform: 
  - Subsystem:

**Comment by onahirniak** [comment] 2021-03-02 13:48
The same issue.

**Comment by abdulmoizlogiciel** [comment] 2022-11-30 11:49
any resolution or workaround please?

**Comment by raman-m** [comment] 2024-03-27 17:21
Duplicate of #1040

**Closed** 2024-03-27 17:28 UTC
