### ISSUE TITLE
Cannot resolve scoped service `KubeClient.IKubeApiClient` from root provider

### ISSUE THREAD

**Issue by Marusyk** [ThreeMammals/Ocelot#977] opened 2019-08-01 11:07 UTC
## Expected Behavior / New Feature

redirect to service in k8s cluster

## Actual Behavior / Motivation for New Feature
> [19-08-01 11:02:11.11Z INF] requestId: 0HLOMDUGQ7EF3:00000004, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /{everything} <s:Development/Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware>
> [19-08-01 11:02:11.11Z INF] requestId: 0HLOMDUGQ7EF3:00000004, previousRequestId: no previous request id, message: No authentication needed for /devices/v1/devices <s:Development/Ocelot.Authentication.Middleware.AuthenticationMiddleware>
> [19-08-01 11:02:11.11Z INF] requestId: 0HLOMDUGQ7EF3:00000004, previousRequestId: no previous request id, message: /{everything} route does not require user to be authorised <s:Development/Ocelot.Authorisation.Middleware.AuthorisationMiddleware>
> [19-08-01 11:02:11.11Z WRN] requestId: 0HLOMDUGQ7EF3:00000004, previousRequestId: no previous request id, message: unabe to find load balancer for /devices/{everything}|Get| exception is System.InvalidOperationException: Cannot resolve scoped service 'KubeClient.IKubeApiClient' from root provider.
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnResolve(Type serviceType, IServiceScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
>    at Ocelot.Provider.Kubernetes.KubernetesProviderFactory.GetkubeProvider(IServiceProvider provider, ServiceProviderConfiguration config, String name, IOcelotLoggerFactory factory)
>    at Ocelot.ServiceDiscovery.ServiceDiscoveryProviderFactory.GetServiceDiscoveryProvider(ServiceProviderConfiguration config, String key)
>    at Ocelot.ServiceDiscovery.ServiceDiscoveryProviderFactory.Get(ServiceProviderConfiguration serviceConfig, DownstreamReRoute reRoute)
>    at Ocelot.LoadBalancer.LoadBalancers.LoadBalancerFactory.Get(DownstreamReRoute reRoute, ServiceProviderConfiguration config)
>    at Ocelot.LoadBalancer.LoadBalancers.LoadBalancerHouse.Get(DownstreamReRoute reRoute, ServiceProviderConfiguration config) <s:Development/Ocelot.LoadBalancer.Middleware.LoadBalancingMiddleware>
> [19-08-01 11:02:11.11Z WRN] requestId: 0HLOMDUGQ7EF3:00000004, previousRequestId: no previous request id, message: Error Code: UnableToFindLoadBalancerError Message: unabe to find load balancer for /devices/{everything}|Get| exception is System.InvalidOperationException: Cannot resolve scoped service 'KubeClient.IKubeApiClient' from root provider.
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnResolve(Type serviceType, IServiceScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
>    at Ocelot.Provider.Kubernetes.KubernetesProviderFactory.GetkubeProvider(IServiceProvider provider, ServiceProviderConfiguration config, String name, IOcelotLoggerFactory factory)
>    at Ocelot.ServiceDiscovery.ServiceDiscoveryProviderFactory.GetServiceDiscoveryProvider(ServiceProviderConfiguration config, String key)
>    at Ocelot.ServiceDiscovery.ServiceDiscoveryProviderFactory.Get(ServiceProviderConfiguration serviceConfig, DownstreamReRoute reRoute)
>    at Ocelot.LoadBalancer.LoadBalancers.LoadBalancerFactory.Get(DownstreamReRoute reRoute, ServiceProviderConfiguration config)
>    at Ocelot.LoadBalancer.LoadBalancers.LoadBalancerHouse.Get(DownstreamReRoute reRoute, ServiceProviderConfiguration config) errors found in ResponderMiddleware. Setting error response for request path:/devices/v1/devices, request method: GET <s:Development/Ocelot.Responder.Middleware.ResponderMiddleware>

## Steps to Reproduce the Problem

Follow this docs https://ocelot.readthedocs.io/en/latest/features/kubernetes.html

`services.AddOcelot(_configuration).AddKubernetes(false); // or true`

My service in k8s: devices-api.dev:10010

Config:
```json
{
    "ReRoutes": [
        {
            "DownstreamPathTemplate": "/{everything}",
            "DownstreamScheme": "http",
            "UpstreamPathTemplate": "/devices/{everything}",
            "ServiceName": "devices-api.dev",
            "UpstreamHttpMethod": [ "Get" ]
        }
    ],
    "GlobalConfiguration": {
        "ServiceDiscoveryProvider": {
            "Namespace": "dev",
            "Type": "kube"
        }
    }
}
```

## Specifications

  - Version: Ocelot 13.5.2, Ocelot.Provider.Kubernetes 13.5.2
  - Platform: Docker
  - Subsystem: ASP.NET Core that runs in docker container in k8s cluster

**Comment by Marusyk** [comment] 2019-08-05 21:55
@TomPallister could you please suggest

**Comment by AmadorSV** [comment] 2019-09-09 18:43
Have you managed to solve this? I'm having the same issue.

**Comment by JakubSlonka** [comment] 2019-10-21 22:26
Any news regarding this issue? I am also having this problem.

**Comment by ussamoo** [comment] 2020-02-08 19:49
Same issue here!

**Comment by ussamoo** [comment] 2020-02-10 14:15
This happen when the KubeClient is not able to load the KUBECONFIG from the cluster during his instantiation (Injection), for example when you are running on a local machine.

**Comment by sergiomcalzada** [comment] 2020-05-06 11:21
That happens because `ServiceDiscoveryFinderDelegate` is registered as a singleton and the `IKubeApiClient` is registered as a scoped.
That error happens on AspNetCore 3.x

**Comment by neetra** [comment] 2020-05-29 11:42
@Marusyk  did you found any solution for this, I am facing this same issue

**Comment by Marusyk** [comment] 2020-05-29 12:41
@neetra 
no, I just don't use it. I run Ocelot in kubernetes but without `AddKubernetes`

**Comment by sergiomcalzada** [comment] 2020-05-29 12:52
Hello, you cant register your own IServiceDiscoveryProvider that initiates a scope before resolving the IKubeApiClient.

Not so elegant because a scope is created every time but It works :)

Another option is to register manually the `IKubeApiClient` as a singleton, but it was a difficult task :/

```
public class KubeKubernetesServiceDiscoveryProvider : IServiceDiscoveryProvider
    {
        private readonly KubeRegistryConfiguration kubeRegistryConfiguration;
        private readonly IOcelotLogger logger;
        private readonly IServiceProvider provider;

        public KubeKubernetesServiceDiscoveryProvider(KubeRegistryConfiguration kubeRegistryConfiguration,
            IOcelotLoggerFactory factory, IServiceProvider provider)
        {
            this.kubeRegistryConfiguration = kubeRegistryConfiguration;
            this.provider = provider;
            this.logger = factory.CreateLogger<KubeKubernetesServiceDiscoveryProvider>();
        }

        public async Task<List<Service>> Get()
        {
            using (var scope = this.provider.CreateScope())
            {
                var kubeClient = scope.ServiceProvider.GetService<IKubeApiClient>();

                this.logger.LogDebug($"call service namespace:{this.kubeRegistryConfiguration.KubeNamespace} service:{this.kubeRegistryConfiguration.KeyOfServiceInK8s}");

                var service = await kubeClient.GetAsync(
                    this.kubeRegistryConfiguration.KeyOfServiceInK8s,
                        this.kubeRegistryConfiguration.KubeNamespace);


                var services = new List<Service>();
                if (service != null)
                {
                    services.Add(new Service(
                        service.Name,
                        new ServiceHostAndPort(service.Host, service.Port),
                        service.Id,
                        service.Version,
                        Enumerable.Empty<string>()));
                }
                else
                {
                    this.logger.LogWarning($"namespace:{this.kubeRegistryConfiguration.KubeNamespace} service:{this.kubeRegistryConfiguration.KeyOfServiceInK8s} not found");
                }

                return services;
            }
        }
    }
```

**Comment by neetra** [comment] 2020-06-09 11:18
@sergiomcalzada 

I created a file named KubeKubernetesServiceDiscoveryProvider and pasted above code, but not able to compile, can you please help me with the which version you are using (I am using Version=2.3.11.0)

_

> 'IKubeApiClient' does not contain a definition for 'GetAsync' and no accessible extension method 'GetAsync' accepting a first argument of type 'IKubeApiClient' could be found (are you missing a using directive or an assembly reference?)

_

**Comment by neetra** [comment] 2020-06-09 11:21
> This happen when the KubeClient is not able to load the KUBECONFIG from the cluster during his instantiation (Injection), for example when you are running on a local machine.

@ussamoo  how do you come to know, how it is loaded?

**Comment by neetra** [comment] 2020-06-09 11:22
> @neetra
> no, I just don't use it. I run Ocelot in kubernetes but without `AddKubernetes`

@Marusyk  what about service discovery?

**Comment by sergiomcalzada** [comment] 2020-06-09 11:41
Sorry, I have a custom "kube-api-envelop" and the code was copied from it and modified. But it is based in the original [file](https://github.com/ThreeMammals/Ocelot/blob/master/src/Ocelot.Provider.Kubernetes/KubeProvider.cs). Instead injecting the "IKubeApiClient", inject the "IServiceProvider" and resolve in a new scope before using it. Something like this

```
 public class KubernetesServiceDiscoveryProvider : IServiceDiscoveryProvider
    {
        private readonly KubeRegistryConfiguration _kubeRegistryConfiguration;
        private readonly IOcelotLogger _logger;
        private readonly IServiceProvider provider;

        public KubernetesServiceDiscoveryProvider(KubeRegistryConfiguration kubeRegistryConfiguration, IOcelotLoggerFactory factory, IServiceProvider provider)
        {
            _kubeRegistryConfiguration = kubeRegistryConfiguration;
            _logger = factory.CreateLogger<KubernetesServiceDiscoveryProvider>();
            this.provider = provider;
        }

        public async Task<List<Service>> Get()
        {
			using(var scope = this.provider.CreateScope()) {
				var _kubeApi = scope.ServiceProvider.GetService<IKubeApiClient>();
				var endpoint = await _kubeApi
					.ResourceClient(client => new EndPointClientV1(client))
					.Get(_kubeRegistryConfiguration.KeyOfServiceInK8s, _kubeRegistryConfiguration.KubeNamespace);

				var services = new List<Service>();
				if (endpoint != null && endpoint.Subsets.Any())
				{
					services.AddRange(BuildServices(endpoint));
				}
				else
				{
					_logger.LogWarning($"namespace:{_kubeRegistryConfiguration.KubeNamespace }service:{_kubeRegistryConfiguration.KeyOfServiceInK8s} Unable to use ,it is invalid. Address must contain host only e.g. localhost and port must be greater than 0");
				}
				return services;
			}
            
        }

        private List<Service> BuildServices(EndpointsV1 endpoint)
        {
            var services = new List<Service>();

            foreach (var subset in endpoint.Subsets)
            {
                services.AddRange(subset.Addresses.Select(address => new Service(endpoint.Metadata.Name,
                    new ServiceHostAndPort(address.Ip, subset.Ports.First().Port),
                    endpoint.Metadata.Uid, string.Empty, Enumerable.Empty<string>())));
            }
            return services;
        }
    }
```

**Comment by sergiomcalzada** [comment] 2020-06-09 11:50
The kube-client library is [dotnet-kube-client](https://github.com/tintoy/dotnet-kube-client) and the file that register the IKubeClient in the injector is [that extension](https://github.com/tintoy/dotnet-kube-client/blob/develop/src/KubeClient.Extensions.DependencyInjection/ClientRegistrationExtensions.cs)

Here you can check from where it reads the configuration and that is registered a scoped services. Maybe check there if the default scope should be scoped or if they want to include a method to change scope.

**Comment by mot256** [comment] 2021-01-29 08:22
We found that the scope error only occurres when environment variable ASPNETCORE_ENVIRONMENT = Development 
I dug a bit deeper and by far the easiest _workaround_ for the issue is by adding this to the host builder:

`webBuilder.UseDefaultServiceProvider(options => options.ValidateScopes = false);`

**Comment by sergiomcalzada** [comment] 2021-01-29 09:16
Hi @mot256 

If you set this setting to false you are going to have an exception at runtime ;)

**Comment by mot256** [comment] 2021-02-01 09:09
> Hi @mot256
> 
> If you set this setting to false you are going to have an exception at runtime ;)

Nope. Works just fine. Its _without_ setting it to false in runtime that we get an issue...

**Comment by raman-m** [comment] 2024-10-21 08:42
### Reopened due https://github.com/ThreeMammals/Ocelot/issues/2178#issuecomment-2424755928

**Comment by raman-m** [comment] 2024-10-21 08:44
@kick2nick, welcome!
Would you mind being assigned? How quickly can you deliver the fix?

**Comment by raman-m** [comment] 2024-10-21 09:33
### Discussed in #1948 
- See https://github.com/ThreeMammals/Ocelot/discussions/1948#discussioncomment-11003234

**Comment by raman-m** [comment] 2024-10-21 09:34
Duplicate of #1470

**Comment by kick2nick** [comment] 2024-10-21 09:41
Hi @raman-m, I'll take that. Need one day if we stick to solution proposed in https://github.com/ThreeMammals/Ocelot/issues/2178#issuecomment-2424755928  - register IKubeApiClient as singleton as far as it already used like singleton.
What about Acceptance Tests? I need to enable scopes validation(hopes it won't break something else), but it also required in https://github.com/ThreeMammals/Ocelot/issues/2178 . Should I wait it?

**Comment by raman-m** [comment] 2024-10-21 09:45
> @mot256 commented [on Feb 1, 2021](https://github.com/ThreeMammals/Ocelot/issues/977#issuecomment-770699973)

Validating scopes is essential, and DI-scopes should also be verified within your solutions.
Sergio has provided a [suitable solution](https://github.com/ThreeMammals/Ocelot/issues/977#issuecomment-641235558) with `provider.CreateScope()`

**Comment by raman-m** [comment] 2024-10-21 10:13
>@kick2nick commented [on Oct 21](https://github.com/ThreeMammals/Ocelot/issues/977#issuecomment-2426152805)
>Hi @raman-m, I'll take that.

Thank you for your intention to contribute!

> Need one day if we stick to solution proposed in https://github.com/ThreeMammals/Ocelot/issues/2178#issuecomment-2424755928  - **register IKubeApiClient as singleton as far as it already used like singleton**.

However, this is not the core issue. The problem lies in the incorrect implementation within the `WithKubernetes` helper. It should be restructured using `ClientRegistrationExtensions`, recycling the options from the constructor as parameters for `ClientRegistrationExtensions`. Is the concept clear?

> What about Acceptance Tests? I need to enable scopes validation (hopes it won't break something else)

Yes, you do! Please enable scope validation.

> but it also required in https://github.com/ThreeMammals/Ocelot/issues/2178 . Should I wait it?

There's no need to wait for the issue mentioned in https://github.com/ThreeMammals/Ocelot/issues/2178. Your focus should be on `Kube` (not `Consul`) and conducting related tests with scope validation disabled. Here's how I see the development process:
- Write a test that reproduces the issue.
- Enable scope validation in the tests, which will likely cause them to fail.
- Implement a fix in the provider.

Again, waiting for anything related to #2178 is unnecessary.

**Comment by kick2nick** [comment] 2024-10-21 16:33
> Sergio has provided a https://github.com/ThreeMammals/Ocelot/issues/977#issuecomment-641235558 with provider.CreateScope()

I have some doubts  about this approach:
- HttpClient MessageHandlers won't be reused - KubeClient [creates](https://github.com/tintoy/dotnet-kube-client/blob/84b055c885a2afe00781559ea400c0bd8cdfce6d/src/KubeClient/KubeApiClient.cs#L213) new one for each KubeApiClient instance, that can cause socket exhaustion issues on heavy loads.
- This scope is separate from request HttpContext scope and no services would be potentially reused.
- There is no option to use long polling with this approach, HttpClient will be [disposed](https://github.com/tintoy/dotnet-kube-client/blob/84b055c885a2afe00781559ea400c0bd8cdfce6d/src/KubeClient/KubeApiClient.cs#L49C9-L49C30) with scope

**Closed** 2024-10-24 17:40 UTC
Labels: bug, Service Discovery, hotfix, Kubernetes, Oct'24
