### ISSUE TITLE
can use RemoteIpAddress in RateLimit?

### ISSUE THREAD

**Issue by majid325** [ThreeMammals/Ocelot#1388] opened 2020-12-07 13:24 UTC
## RateLimitOptions

can we use RemoteIpAddress in RateLimit?

## Specifications

  - Version:16.0.1
  - Platform:.netcore 5
  - Subsystem:

**Comment by raman-m** [comment] 2024-03-17 17:08
Will you contribute to deliver this feature?

**Comment by raman-m** [comment] 2024-03-17 17:08
Duplicate of #1050

**Closed** 2024-03-17 17:09 UTC
