### ISSUE TITLE
Websocket authentication token

### ISSUE THREAD

**Issue by Rakiah** [ThreeMammals/Ocelot#718] opened 2018-12-14 14:12 UTC
Hello, I'm currently using the websocket proxying feature which is working correctly but I would require my system to run a bit of code to check for token validity and token existence, from what I understand this is not implemented, where should I start to implement this kind of feature myself, or is someone already working on something similar ?

I was planning to use a query parameter retrieved by the HttpContext to check for this (I can already do that at micro-service level, but it would be better to do it at gateway level)

**Comment by Rakiah** [comment] 2018-12-17 13:02
Merge request opened for this issue

**Comment by raman-m** [comment] 2024-06-15 13:05
Will be fixed in #1040

**Comment by raman-m** [comment] 2024-06-15 13:05
Duplicate of #1040

**Closed** 2024-06-15 13:05 UTC
Labels: feature, help wanted, proposal
