### ISSUE TITLE
LoadBalancer causes 401 Unauthorized error

### ISSUE THREAD

**Issue by candreouTrade** [ThreeMammals/Ocelot#1203] opened 2020-04-16 14:18 UTC
## Expected Behavior / New Feature
When adding the Roundrobin Loadbalancer option to the ocelot.config.
The gateway should reroute to the downstream microservice without an authorization error

## Actual Behavior / Motivation for New Feature
When adding the Roundrobin Loadbalancer option to the ocelot.config.
I get an 401 authorization error when being routed to the downstream microservice

## Steps to Reproduce the Problem

  1. I have 2 instances of the same downstream Microservice. The Microservice has Windows Authentication enabled.
  2. In my Gateway I have the Ocelot.config DownstreamHostAndPorts section point to both the MicroServices.
  3. If I start the gateway and try to connect to the UpstreamPathTemplate path, I successfully get routed to the downstream microservice.
4. Now, if i add LoadBalancerOptions": { "Type": "RoundRobin" }, to the Ocelot.config and try to connect to the UpstreamPathTemplate, I get a 401 Unauthorized error.

**Comment by candreouTrade** [comment] 2020-04-20 13:41
I've looked into this further and it seems that the load balancer (Round Robin) gets called muliple times for one GET request.  This is causing the URL Re-Route to keep changing. Any idea why this happens?

**Comment by jpj90** [comment] 2020-10-09 07:18
@candreouTrade you might be interested in the same issue as I am (also dealing with Windows Authentication): https://github.com/ThreeMammals/Ocelot/issues/657

**Comment by raman-m** [comment] 2024-03-23 16:38
@candreouTrade 
>I have 2 instances of the same downstream Microservice. The Microservice has **Windows Authentication enabled**.

As @jpj90 said, it could be Win Auth issue on 99%. So, this issue will be fixed as a part of #657 by PR #1521

**Comment by raman-m** [comment] 2024-03-23 16:38
Duplicate of #657

**Closed by raman-m** 2024-03-23 16:38 UTC
