### ISSUE TITLE
Incorrect Routing when a configuration exists with query param wildcard

### ISSUE THREAD

**Issue by garv-daga** [ThreeMammals/Ocelot#2132] opened 2024-08-01 09:44 UTC
Ocelot now matches routes incorrectly.
This started breaking between versions 22.0.1 and 23.0.0.

If I have two configurations - 

```json
{
  "Routes": [
    {
      "DownstreamHostAndPorts": [
        {
          "Host": "{Endpoint1}"
        }
      ],
      "DownstreamPathTemplate": "/api/v1/abc?{everything}",
      "DownstreamScheme": "https",
      "UpstreamPathTemplate": "/api/v1/abc?{everything}"
    },
    {
      "DownstreamHostAndPorts": [
        {
          "Host": "{Endpoint2}"
        }
      ],
      "DownstreamPathTemplate": "/api/v1/{everything}",
      "DownstreamScheme": "https",
      "UpstreamPathTemplate": "/api/v1/abc2/{everything}"
    }
  ]
}
```

Now if I initiate a call with `/api/v1/abc2/apple?isRequired=1` 

Expected Route: `{Endpoint2}/api/v1/apple?isRequired=1`

Actually Routes to: `{Endpoint1}/api/v1/abc?isRequired=1"`

Similar issue reported in: _Originally posted by @Burgyn in https://github.com/ThreeMammals/Ocelot/discussions/2065_

**Comment by raman-m** [comment] 2024-08-01 11:19
Duplicate of #2064

**Comment by raman-m** [comment] 2024-08-01 11:21
Thanks for reporting this! Are you C# developer?

**Comment by garv-daga** [comment] 2024-08-01 11:41
> Thanks for reporting this! Are you C# developer?

Thanks, Yes C# developer.

**Comment by raman-m** [comment] 2024-08-01 11:50
Could you look into the issue by debugging the solution and examining Ocelot's code when you have some spare time, please?
I am currently swamped with tasks for the [v23.3 Hotfixes](https://github.com/ThreeMammals/Ocelot/milestone/8). I anticipate an open PR that will shed light on the issue, which I suspect might be related to a `Regex` problem.

**Comment by lelloz0** [comment] 2024-09-20 08:12
This is also happening for Scopes. If I have two routes where the first is a wildcard for the second, the scopes assigned to the wildcard route allows me to access the second one and not viceversa

**Comment by raman-m** [comment] 2024-09-21 10:21
Hello Raffaele,
Why did you delete your comment from issue #2132?
Please be aware that using wildcards is not supported in Ocelot templates
or placeholders.
If you encounter any unusual behavior with special characters, please let
us know.

**Comment by pwshfan** [comment] 2024-09-21 10:30
> @lelloz0 Hello Raffaele, Why did you delete your comment from issue #2132? Please be aware that using wildcards is not supported in Ocelot templates or placeholders. If you encounter any unusual behavior with special characters, please let us know.

I realized the issue is indeed somewhere else and not related to the wildcards. Thanks for the follow up!

**Comment by raman-m** [comment] 2024-09-21 11:18
@pwshfan, okay, we will concentrate on the [originally reported bug](https://github.com/ThreeMammals/Ocelot/issues/2132#issue-2441996763). Feel free to report any [issues](https://github.com/ThreeMammals/Ocelot/issues), but please create new ones.

**Comment by raman-m** [comment] 2024-11-08 09:53
@int0x81, welcome to your assignment!

**Closed** 2024-12-10 11:33 UTC
Labels: bug, high, Routing, NET9
