### ISSUE TITLE
Reroute sending empty Content-Type which causes Bad request

### ISSUE THREAD

**Issue by vasicvuk** [ThreeMammals/Ocelot#464] opened 2018-07-11 08:16 UTC
## Expected Behavior / New Feature

When sending Http get request from ocelot to downstream. Content-Type should not be sent.

## Actual Behavior / Motivation for New Feautre
Currently there is an empty Content-Type header sent. Also Content-Length: 0 is extra too. This causes for most APIs made in Java to give 400 Bad request since they don't have formatter for Content-Type empty string. Sample:

![image](https://user-images.githubusercontent.com/5639877/42561771-412067f0-84fa-11e8-86a5-c912e6b9f591.png)

## Steps to Reproduce the Problem

  1. Install Fidler
  2. Trace reroute to downstream
  3. See empty content type and length in request headers

## Specifications

  - Version: 8.0.0
  - Platform: Windows 10 x64
  - Subsystem: .Net core 2.1

**Comment by TomPallister** [comment] 2018-07-12 19:05
@vasicvuk thanks for your interest in the project! Mmmmmmmm I didn't even realise I'm adding these on...I think the issue is in RequestMapper.cs but not 100%. It looks like the Content-Type header is added there but I cannot find where the Content-Length header is being added.

This should be pretty easy to fix and will just need some debugging to work it out.

**Comment by TomPallister** [comment] 2018-07-12 19:09
Ill try get it fixed asap

**Comment by vasicvuk** [comment] 2018-07-12 19:32
@TomPallister  thank you for quick response. I will try to debug it too in order to see where the problem is.

**Comment by vasicvuk** [comment] 2018-07-12 20:15
Seems like HttpRequest by default has System.IO.Stream+NullStream not null. So the headers are added anyway since request.Body is never null. https://github.com/ThreeMammals/Ocelot/blob/a15f75dda80003481661f67b2610fc42f96b1c90/src/Ocelot/Request/Mapper/RequestMapper.cs#L41

Still not sure how Content-Length is added but maybe it is added by default if Content-Type is provided.

Here is the little test i made to see what is value of body:
```
           DefaultHttpRequest defaultHttp = new DefaultHttpRequest(CreateHttpContext())
            {
                Method = HttpMethods.Get,
                Protocol = "https",
                Host = new HostString("samplehost"),
                Path = "/api/cockpit/plugin/asseco/static/app/plugin.js",
                ContentType = " "
            };
            if(defaultHttp.Body == null) {
                Console.WriteLine("Body is null");
            } else {
                Console.WriteLine("Body is not null " + defaultHttp.Body);
            }
```

This test returns: Body is not null System.IO.Stream+NullStream

**Comment by TomPallister** [comment] 2018-07-12 20:24
@vasicvuk yep as expected that is the problem area! :)

**Comment by mciureanu** [comment] 2018-07-16 10:15
The same thing happens when running Ocelot and the API in the same process with aspnet core 2.1 Ocelot adds this empty header causing the API to fail. I have added a middleware to remove this empty header to avoid this problem

**Comment by TomPallister** [comment] 2018-07-17 19:43
@vasicvuk sorry I have not fixed this yet, I have been away for a few days! Will get on it ASAP.

**Comment by TomPallister** [comment] 2018-07-17 20:21
@vasicvuk what are you hosting Ocelot with e.g. Linux / Windows? Is there anything in front of Kestrel e.g. IIS / nginx? 

When I debug Ocelot I Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameRequestStream as the type for a stream when I curl with GET so no body. 

I think there is might be some .net core magic here to contend with!

**Comment by TomPallister** [comment] 2018-07-17 20:22
There are also ConentType and ContentLength properties on the request object...I guess I could use them to say if they don't exist then definitely don't add any content.

**Comment by vasicvuk** [comment] 2018-07-18 04:40
I use .Net Core 2.1 running it with IIS through Visual Studio 2017 Community.

**Comment by TomPallister** [comment] 2018-07-18 05:52
Ok cool, I will keep looking!

**Comment by vasicvuk** [comment] 2018-07-18 09:07
I guess that you can trim it when Content-Length is 0 but it would be nice to know what is causing an issue

**Comment by TomPallister** [comment] 2018-07-18 17:07
@vasicvuk I think NullStream is an internal type so you cant check or instantiate it. I also think it is only set when you instantiate DefaultHttpRequest...not when you receive an actual HttpRequest!

**Comment by TomPallister** [comment] 2018-07-21 08:30
Released in version 8.0.1

**Closed by TomPallister** 2018-07-21 08:30 UTC
Labels: bug, good first issue, help wanted, merged, small effort

**Comment by vasicvuk** [comment] 2018-07-21 09:43
Confirming that everything works now! 👍

**Comment by TomPallister** [comment] 2018-07-21 10:03
sweet
