### ISSUE TITLE
ReRoute by header value

### ISSUE THREAD

**Issue by aringlot** [ThreeMammals/Ocelot#624] opened 2018-09-19 05:32 UTC
## Expected Behavior / New Feature
ReRoute discovery by header value in addition to path.

## Actual Behavior / Motivation for New Feature
I am working on versioning problem for API, that is already running in production.
By the current moment version is passed with every request|response via headers.

I would like to configure Ocelot in a such way, so that v1 will be routed to Api 1, v2 to Api 2 an so on.
It also seems that additional constraints on Path could be used in other scenarios.

I can think about following problem with this approach:
should filtering be done by all headers, that are present in ReRoute or should it be one of the list ?

## Current implementation
Right now I achieve the behaviour above by adding middleware. But this seems to be a bad solution.
Dear colleagues, is it possible to achieve described behaviour in any other way ?

**Comment by TomPallister** [comment] 2018-09-19 06:38
@aringlot I think this is a duplicate of #360. I will copy your content over and reference this ticket. 

Please share your middleware? Perhaps we can use this as a basis for the feature!

**Closed by TomPallister** 2018-09-19 06:38 UTC

**Comment by aringlot** [comment] 2018-09-19 07:34
@TomPallister Thank you for you feed back!
I went through #360. It seems that mine solution is even worth than #360. 

```
    public class ApiVersionHeaderMiddleware
    {
        private const string ApiVersionHeader = "X-Api-Version";

        private readonly RequestDelegate _next;

        public ApiVersionHeaderMiddleware(RequestDelegate next)
        {
            _next = next;
        }

        public Task Invoke(HttpContext httpContext)
        {

            if (httpContext.Request.Headers.TryGetValue(ApiVersionHeader, out var version))
            {
                httpContext.Request.Path = new PathString($"/{version}{httpContext.Request.Path}");
            }

            return _next(httpContext);
        }
    }
```
In addition to that there is a ReRoute configuration, that looks like following /{version}/{path}

I am also thinking about doing some coding to add headers to ReRoute configuration and modify your ReRoute discovery routine. But I need your approval.

**Comment by TomPallister** [comment] 2018-09-20 06:03
@aringlot I would welcome a PR, if you do make one please have unit and acceptance tests and if possible update the docs. I’m. How would you make the JSON look?

**Comment by aringlot** [comment] 2018-09-20 12:34
I am thinking about adding additional field to ReRoute like following:
```
ReRoute: {
  UpStreamHeaders:[ { Header1: "header1"}, { Header2: "Header2"}]
}
```

there is a problem with such approach - all headers should be present to much ReRoute. Probably there should be another field to specify either it should be AND or OR operand. By adding such field I try to reduce amount of ReRoutes needed for different sets of headers.

**Comment by TomPallister** [comment] 2018-09-20 17:15
You want something where you can use the header values in the UpstreamPathTemplate I think...not sure how it would look.

**Comment by raman-m** [comment] 2023-06-28 18:40
@aringlot  Hi Oleksandr!

Would you like to fight for your solution? 😉

**Comment by aringlot** [comment] 2023-07-19 14:04
Hi @raman-m 
no, I am not going to fight for my solution. I am not an active user of the Ocelot anymore and out of context. 

I believe there are already better solutions for the original problems.

**Comment by raman-m** [comment] 2023-07-19 15:23
> @aringlot commented [on July 19](#issuecomment-1642153735)

OK I understand, regarding this issue. Now we have v19 which is .NET 7 release with a lot of features including headers transforms.

Do you have an intention to contribute to Ocelot project?

If Yes,
Could you [Sync fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) please? Your fork is old and [it should be synced](/aringlot/Ocelot/compare/develop...ThreeMammals:Ocelot:develop)!
