### ISSUE TITLE
Errors when running Ocelot.Provider.Kubernetes in Azure K8

### ISSUE THREAD

**Issue by tomfanara** [ThreeMammals/Ocelot#1527] opened 2021-10-17 04:11 UTC
## Expected Behavior / New Feature

Expect downstream routing to work

## Actual Behavior / Motivation for New Feature

404 error 

Error Code: UnableToFindServiceDiscoveryProviderError Message: Unable to find service discovery provider for type: consul errors found in ResponderMiddleware. Setting error response for request path:/products/g-ps4, request method: GET

## Steps to Reproduce the Problem

  1. routing file
```json
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/home",
      "DownstreamScheme": "http",

      "UpstreamPathTemplate": "/test",
      "ServiceName": "productshttpaggegator",
      "UpstreamHttpMethod": [ "Get" ]
    },
    {
      "DownstreamPathTemplate": "/api/products/{postId}",
      "DownstreamScheme": "http",

      "UpstreamPathTemplate": "/products/{postId}",
      "ServiceName": "productshttpaggegator",
      "UpstreamHttpMethod": [ "Get" ]
    },

    "GlobalConfiguration",
    {
      "ServiceDiscoveryProvider": {
        "Namespace": "apigateway",
        "Type": "kube"
      }
    }
  ]
}
```
  2. API Gateway pod or service configured as LoadBalancer

## Specifications
  - Version:  Ocelot 17.0.0 and Ocelot.Provider.Kubernetes 17.0.0
  - Platform: Azure Kubernetes cluster
  - Subsystem: .NET 5 API project

**Comment by leaosomogyi-atlas** [comment] 2022-07-07 14:07
Any update? Because of this i got stuck on version `14.1.0` when all works

**Comment by tomfanara** [comment] 2022-07-07 18:44
Hi Felipe hope all is well. I gave up on Ocelot on K8 but I still use it in dev for Docker Compose. I just use a Ingress Controller in K8 instead and load balance from their and wired in Identity with a JWT.
However, I liked the simplicity of Ocelot with DI. I'll be back under the hood soon.

I am not sure they are still supporting Ocelot although Microsoft is endorsing it in their microservices book.

thanks,
Tom


________________________________

**Comment by raman-m** [comment] 2024-01-13 17:43
@ggnaegi 
Yet another the same error. Pairing K8 vs Consul...
Maybe load balancer?

**Comment by ggnaegi** [comment] 2024-01-14 22:19
@raman-m Ok, yes, the problem is here https://github.com/ThreeMammals/Ocelot/blob/bb795876c493af958f1d58c852ea56e94263906d/src/Ocelot/ServiceDiscovery/ServiceDiscoveryProviderFactory.cs#L59
The design isn't great and should be addressed in the future. Since the class used for the k8 provider is called ```KubernetesServiceDiscoveryProvider```
It will never match with ```kube```...

**Comment by raman-m** [comment] 2024-01-15 10:15
@ggnaegi  🆗 You know this logic better than me.
I'm going to accept the bug...

----
> The design isn't great and should be addressed in the future. Since the class used for the k8 provider is called ```KubernetesServiceDiscoveryProvider```. It will never match ```kube```... 

Oh, oh! Ups!... Yeap, design is not great. But [K8 SD feature](https://ocelot.readthedocs.io/en/latest/features/kubernetes.html) works in general, right?
But isn't `ServiceDiscoveryFinderDelegate` responsible for getting correct provider instance?
Maybe the author forgot to follow instructions in [Kubernetes](https://ocelot.readthedocs.io/en/latest/features/kubernetes.html) doc, and adding reference to `Ocelot.Provider.Kubernetes` package and calling `AddKubernetes` method? 😄

**Comment by raman-m** [comment] 2024-01-15 10:18
@tomfanara Did you follow the instructions in [Kubernetes](https://ocelot.readthedocs.io/en/latest/features/kubernetes.html) doc? 😉

**Closed** 2024-02-12 09:17 UTC
Labels: bug, accepted, Service Discovery, Nov'23, Kubernetes
