### ISSUE TITLE
the configuration of Ocelot made error

### ISSUE THREAD

**Issue by yuchen1030** [ThreeMammals/Ocelot#400] opened 2018-06-13 08:56 UTC
## Expected Behavior / New Feature
When I update  Ocelot version from  1.4.2  to 7.0.4 and add some configuration item, it make some error.
  1.    DownstreamPathTemplate :  /api/ControllerName/ActionName/{url}  . It report 404 error . I must 
        write it as   /api/ControllerName/ActionName   or    /api/ControllerName/{url}  .   why ?  How should I use   /{url}   format? 

  2.     ```"FileCacheOptions": { "TtlSeconds":  0 }```.
When the value is not 0 ,  the first request is OK, but then it will report  error 500 if continue request.

## Steps to Reproduce the Problem

  - Version:7.0.4
  - Platform:.NET CORE2.0, windows7 os.
  - Subsystem:

**Comment by TomPallister** [comment] 2018-06-13 17:53
@yuchen1030 there are lots of changes between Ocelot 1.4.2 and 7.0.4. Have you updated your configuration to account for them?

Maybe paste your configuration json here and I will take a look?

**Comment by yuchen1030** [comment] 2018-06-14 00:46
Thanks. My config it like this:
{
  "ReRoutes": [
    //GetBasicUserInfo
    { //http://192.168.0.229:9000/api/HM_Employees/GetBasicUserInfo?workNum=B0182
      "DownstreamPathTemplate": "/api/HM_Employees/GetBasicUserInfo",
      //"DownstreamPathTemplate": "/api/HM_Employees/GetBasicUserInfo/{url}", //error
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/api/HM_Employees/GetBasicUserInfo",
      "UpstreamHttpMethod": [ "GET" ],
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "hrApiKey",
        "AllowedScopes": [ "HRWebAPI" ]
      },
      "ServiceName": "HRWebAPI",
      "LoadBalancerOptions": { "Type": "RoundRobin" }, // RoundRobin ，LeastConnection
      "UseServiceDiscovery": true,
      "ReRouteIsCaseSensitive": false,
      "RateLimitOptions": {
        "ClientWhitelist": [], 
        "EnableRateLimiting": true, 
        "Period": "300s", 
        "PeriodTimespan": 10, 
        "Limit": 100 
      },
      "QoSOptions": {
        "ExceptionsAllowedBeforeBreaking": 3,
        "DurationOfBreak": 10,
        "TimeoutValue": 9000
      }
      //,"FileCacheOptions": { "TtlSeconds": 1 }   //it will error 
    },

    //IdentifyServer4 config： /Connect/Token
    {
      "DownstreamPathTemplate": "/{url}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "192.168.0.210",
          "Port": 9600
        }
      ],
      "UpstreamPathTemplate": "/Auth/{url}",
      "UpstreamHttpMethod": [ "Get", "Post" ]
    }
  ],

  //global config
  "GlobalConfiguration": {
    //consul config
    "ServiceDiscoveryProvider": {
      "Host": "192.168.5.73",
      "Port": 8500
    }
  }

}

**Comment by yuchen1030** [comment] 2018-06-14 00:48
`{
  "ReRoutes": [
    //GetBasicUserInfo
    { //http://192.168.0.229:9000/api/HM_Employees/GetBasicUserInfo?workNum=B0182
      "DownstreamPathTemplate": "/api/HM_Employees/GetBasicUserInfo",
      //"DownstreamPathTemplate": "/api/HM_Employees/GetBasicUserInfo/{url}", //error
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/api/HM_Employees/GetBasicUserInfo",
      "UpstreamHttpMethod": [ "GET" ],
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "hrApiKey",
        "AllowedScopes": [ "HRWebAPI" ]
      },
      "ServiceName": "HRWebAPI",
      "LoadBalancerOptions": { "Type": "RoundRobin" }, // RoundRobin ，LeastConnection
      "UseServiceDiscovery": true,
      "ReRouteIsCaseSensitive": false,
      "RateLimitOptions": {
        "ClientWhitelist": [], 
        "EnableRateLimiting": true, 
        "Period": "300s", 
        "PeriodTimespan": 10, 
        "Limit": 100 
      },
      "QoSOptions": {
        "ExceptionsAllowedBeforeBreaking": 3,
        "DurationOfBreak": 10,
        "TimeoutValue": 9000
      }
      //,"FileCacheOptions": { "TtlSeconds": 1 }   //it will error 
    },

    //IdentifyServer4 config： /Connect/Token
    {
      "DownstreamPathTemplate": "/{url}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "192.168.0.210",
          "Port": 9600
        }
      ],
      "UpstreamPathTemplate": "/Auth/{url}",
      "UpstreamHttpMethod": [ "Get", "Post" ]
    }
  ],

  //global config
  "GlobalConfiguration": {
    //consul config
    "ServiceDiscoveryProvider": {
      "Host": "192.168.5.73",
      "Port": 8500
    }
  }

}`

**Comment by TomPallister** [comment] 2018-06-14 06:50
@yuchen1030 

1. I cannot see these options in your configuration. Are you still having a problem with this? The {url} format is a placeholder. Please read the docs [here](http://ocelot.readthedocs.io/en/latest/features/routing.html#) to see how it works.

2. What error do you get from Ocelot when having problems with the cache option?

**Comment by yuchen1030** [comment] 2018-06-14 12:47
Thank for your reply.
    I konw the using of {url}.
    When FileCacheOptions not zero, continue request will error. The ocelot window like this: Ocelot.Error.Middleware.ExceptionHandlerMiddleware[0]...The formate of value '-1' is invalid. The error picture in https://raw.githubusercontent.com/yuchen1030/IssueList/master/IssueList/Images/ocelot%20window%20when%20cache%20error.png

**Comment by TomPallister** [comment] 2018-06-14 17:32
@yuchen1030 ahh OK thanks for this.

There is code in Ocelot that maps the cached response into a HttpResponseMessage and something is failing here around one of the headers that has been cached. Are you able to paste the headers that are being cached here so I can work out what the problem is?

**Comment by yuchen1030** [comment] 2018-06-15 03:57
Thank you very much.
It's like what you say. I add the ocelot 7.0.4 source code project to my gateway sln, I found that the strange header field Expires="-1".
My step is as follow:
1. prepare test Routes as follow:
    //HRWebAPI Health check
    { //http://192.168.0.210:9000/api/Health/Get
       "DownstreamPathTemplate": "/api/Health/{url}",   //when this is webapi url,it is error
      // "DownstreamPathTemplate": "/Home/Index",    //when this is mvc url,it is ok.
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/HR/Health/{url}",
      "UpstreamHttpMethod": [ "Get", "Post" ],
      "ServiceName": "HRWebAPI",
      "LoadBalancerOptions": { "Type": "RoundRobin" },
      "UseServiceDiscovery": true,
      "ReRouteIsCaseSensitive": false,
      "RateLimitOptions": {
        "ClientWhitelist": [],
        "EnableRateLimiting": true,
        "Period": "300s",
        "PeriodTimespan": 10,
        "Limit": 100
      },
      "QoSOptions": {
        "ExceptionsAllowedBeforeBreaking": 3,
        "DurationOfBreak": 10,
        "TimeoutValue": 9000
      },
      "FileCacheOptions": { "TtlSeconds": 234 }
    },
2.  the micro service is as follow: 
the mvc url ui(Home Index)    https://github.com/yuchen1030/IssueList/blob/master/IssueList/Images/the%20mvc%20url%20ui(Home%20Index).png?raw=true
the webapi code(Health Get)   https://github.com/yuchen1030/IssueList/blob/master/IssueList/Images/the%20webapi%20code(Health%20Get).png?raw=true

3. request /HR/Health/Get in postman again , the ocelot window indicate the \Ocelot\Cache\Middleware
OutputCacheMiddleware.cs Line 91(streamContent.Headers.Add(header.Key, header.Value))  error. 
The related pictures are: 
the ocelot windows when error(with ocelot code) 
 https://github.com/yuchen1030/IssueList/blob/master/IssueList/Images/the%20ocelot%20windows%20when%20error(with%20ocelot%20code).png?raw=true 
cache error when webapi url   https://github.com/yuchen1030/IssueList/blob/master/IssueList/Images/cache%20error%20when%20webapi%20url.png?raw=true
the postman ui when webapi url request again  https://github.com/yuchen1030/IssueList/blob/master/IssueList/Images/the%20postman%20ui%20when%20webapi%20url%20request%20again.png?raw=true
4. use MVC url in Routes /DownstreamPathTemplate , it is OK ,no matter how many times request it.
The related pictures are: 
cache ok when MVC url         https://github.com/yuchen1030/IssueList/blob/master/IssueList/Images/cache%20ok%20when%20MVC%20url.png?raw=true
the postman ui when mvc url request again  https://github.com/yuchen1030/IssueList/blob/master/IssueList/Images/the%20postman%20ui%20when%20mvc%20url%20request%20again.png?raw=true

All the related  pictures are in  https://github.com/yuchen1030/IssueList/tree/master/IssueList/Images . 

Comparison of correct and wrong , cached.ContentHeaders in OutputCacheMiddleware.cs is different, 
 the response Headers in postman is different. I don't know why.

**Comment by TomPallister** [comment] 2018-06-15 06:12
@yuchen1030 ok cool I will try this header.

Don’t use postman for testing APIs headers it adds its own headers and does things you are not aware of. Curl is better!

**Comment by yuchen1030** [comment] 2018-06-15 07:07
Thank you for your suggestion. 
I try it and found that curl  has the same performance and response header and result as postman/Google Chrome.

**Comment by TomPallister** [comment] 2018-06-15 07:19
@yuchen1030 I have a PR to fix this issue and will let you know when it has been merged and released.

**Comment by yuchen1030** [comment] 2018-06-15 07:27
OK,I know. 
Thanks for your quick feedback and outstanding work !

**Comment by TomPallister** [comment] 2018-06-22 06:44
Released in 7.0.6

**Closed by TomPallister** 2018-06-22 06:44 UTC
Labels: bug, good first issue, merged, small effort
