### ISSUE TITLE
Bug with catch-all routing

### ISSUE THREAD

**Issue by istanko** [ThreeMammals/Ocelot#2169] opened 2024-10-09 20:26 UTC
Hello,

I have a problem with two get routes. One of them is not getting hit.

## Expected Behavior / New Feature
With the following configuration, expected behavior should be that calling /api/products?query=test is redirected to the downstream path template /api/products?query=test, and that calling /api/products/1 is redirected to the downstream path template /api/products/1

```json
{
  "UpstreamPathTemplate": "/api/products?{everything}",
  "UpstreamHttpMethod": [
    "Get",
    "Options"
  ],
  "DownstreamPathTemplate": "/api/products-something?{everything}",
  "DownstreamScheme": "http",
  "DownstreamHostAndPorts": [
    {
      "Host": "localhost",
      "Port": 80
    }
  ]
},
{
  "UpstreamPathTemplate": "/api/products/{id}",
  "UpstreamHttpMethod": [
    "Get",
    "Options"
  ],
  "DownstreamPathTemplate": "/api/products/{id}",
  "DownstreamScheme": "http",
  "DownstreamHostAndPorts": [
    {
      "Host": "localhost",
      "Port": 80
    }
  ]
}
```

## Actual Behavior / Motivation for New Feature
Calling /api/products/1 will be routed to downstream path template /api/products?1

## Steps to Reproduce the Problem

Use the provided configuration and make calls to both endpoints.

## Specifications

  - Version: 23.3.4
  - Platform: .NET 8
  - Subsystem: Windows

**Comment by raman-m** [comment] 2024-10-10 11:19
> ```json
> {
>   "UpstreamPathTemplate": "/api/products?{everything}",
>   "DownstreamPathTemplate": "/api/products-something?{everything}",
>  },
> {
>   "UpstreamPathTemplate": "/api/products/{id}",
>   "DownstreamPathTemplate": "/api/products/{id}",
> }
> ```
> 

The configuration appears to be slightly incorrect. The 2nd route is a catch-all, while the first route processes all query strings. Defining the 1st route when the 2nd one is a catch-all seems redundant, as the 2nd route should be able to process all URLs from the first route, including all query strings.

Merging both routes into one could be done as follows:
```json
{
  "UpstreamPathTemplate": "/api/products/{everything}",
  "DownstreamPathTemplate": "/api/products/{everything}",
}
```
Wouldn't this approach be effective?

**Comment by raman-m** [comment] 2024-10-10 11:20
Please read this doc carefully &rarr; [Empty Placeholders](https://ocelot.readthedocs.io/en/latest/features/routing.html#empty-placeholders)

**Comment by raman-m** [comment] 2024-10-10 11:35
> ### Actual Behavior / Motivation for New Feature
> Calling /api/products/1 will be routed to downstream path template /api/products?1
> 
> ### Steps to Reproduce the Problem
> Use the provided configuration and make calls to both endpoints.
> 

Are you sure? 😉 
Please attach logs of your testing session with log level `Debug`
And we will continue this funny talk...

----
> Calling /api/products/1 will be routed to downstream path template /api/products?1

This ought to be verified by our routing tests, and it's concerning if it's not, as it may indicate a bug.
Yes, you've reported the old problem: here is more Routing fun
- #2134 
- #2064 
- #2132

**Comment by raman-m** [comment] 2024-10-10 11:36
Duplicate of #2132

**Comment by raman-m** [comment] 2024-10-10 11:49
> Thanks for reply. The problem here is that the downstream route is different.

OK, but when you have one service instance with different downstream paths, why do merge paths in upstream?
You have to have different upstream paths too!
Your final solution is:
```json
{
  "UpstreamPathTemplate": "/api/products-something?{everything}",
  "DownstreamPathTemplate": "/api/products-something?{everything}",
},
{
  "UpstreamPathTemplate": "/api/products/{id}",
  "DownstreamPathTemplate": "/api/products/{id}",
}
```
and moreover, it must be one Catch All route ❗ 
```json
{
  "UpstreamPathTemplate": "/{everything}",
  "DownstreamPathTemplate": "/{everything}",
},
```
Don't say "thank you"

**Comment by raman-m** [comment] 2024-10-10 11:51
Mr. I, what's your full name?
How do you use Ocelot now? Learning?
Do you have Ocelot app in Production environment?

**Comment by istanko** [comment] 2024-10-10 12:00
> > Thanks for reply. The problem here is that the downstream route is different.
> 
> OK, but when you have one service instance with different downstream paths, why do merge paths in upstream? You have to have different upstream paths too! Your final solution is:
> 
> ```json
> {
>   "UpstreamPathTemplate": "/api/products-something?{everything}",
>   "DownstreamPathTemplate": "/api/products-something?{everything}",
> },
> {
>   "UpstreamPathTemplate": "/api/products/{id}",
>   "DownstreamPathTemplate": "/api/products/{id}",
> }
> ```
> 
> and moreover, it must be one Catch All route ❗
> 
> ```json
> {
>   "UpstreamPathTemplate": "/{everything}",
>   "DownstreamPathTemplate": "/{everything}",
> },
> ```
> 
> Don't say "thank you"

The thing here is that the {id} should not be Catch All, but placeholder for variable.

**Comment by raman-m** [comment] 2024-10-26 11:36
Mr. @istanko, will you open a PR in November'24?

**Comment by raman-m** [comment] 2024-11-08 09:56
@int0x81, welcome to your assignment!

**Comment by ggnaegi** [comment] 2024-11-13 08:44
@istanko could you please check if you observe the same behavior with https://github.com/ThreeMammals/Ocelot/pull/2200? Thanks

**Closed** 2024-12-10 11:33 UTC
Labels: bug, Configuration, Routing, NET9
