### ISSUE TITLE
限流部分有明显的BUG

### ISSUE THREAD

**Issue by leeon201314** [ThreeMammals/Ocelot#923] opened 2019-06-13 01:15 UTC
Ocelot.RateLimit.RateLimitCore 第37行
if (entry.Value.Timestamp + TimeSpan.FromSeconds(rule.PeriodTimespan) >= DateTime.UtcNow)
应该是
if (entry.Value.Timestamp + ConvertToTimeSpan(rule.Period) >= DateTime.UtcNow)

**Comment by raman-m** [comment] 2024-01-21 13:44
Duplicate of #910

**Comment by raman-m** [comment] 2024-01-21 13:45
Duplicate of #1590

**Comment by raman-m** [comment] 2024-01-21 13:46
Will be fixed by #1592

**Closed by raman-m** 2024-01-21 13:46 UTC
Labels: bug, Rate Limiting
