### ISSUE TITLE
ServiceDiscoveryProvider kubernetes provider 

### ISSUE THREAD

**Issue by yoramda** [ThreeMammals/Ocelot#1291] opened 2020-07-16 22:20 UTC
## Expected Behavior 
Can you please clarify how to get the, host, port. and token info from the Kubernetes environment ?
"GlobalConfiguration": {
    "ServiceDiscoveryProvider": {
      "Host": "10.10.12.225",
      "Port": 443,
      "Token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "Namespace": "dev-ns",
      "Type": "kube"
    }
  }

Thanks.

## Specifications

  - Version: 16.0.1
  - Platform: netcore + linux
  - Subsystem:

**Comment by shawnwildermuth** [comment] 2020-10-03 22:07
The problem is that the type needs to be the complete name of the provider (the docs don't reflect this, I am going to do a PR to fix this). Put Type: "KubernetesServiceDiscoveryProvider" instead of kube.

**Comment by tomfanara** [comment] 2021-10-18 20:28
Hello did anybody have any luck at this? I have tried reading the docs over and over and cannot get it to work. It works in Docker. I am having the same issue. Here is my routing file. Also do I need RBAC setup?

{
"ReRoutes": [
{
"DownstreamPathTemplate": "/home",
"DownstreamScheme": "http",
"UpstreamPathTemplate": "/test",
"ServiceName": "productshttpaggegator",
"UpstreamHttpMethod": [ "Get" ]
},
{
"DownstreamPathTemplate": "/api/products/{postId}",
"DownstreamScheme": "http",
"UpstreamPathTemplate": "/products/{postId}",
"ServiceName": "productshttpaggegator",
"UpstreamHttpMethod": [ "Get" ]
}
],
"GlobalConfiguration": {
"ServiceDiscoveryProvider": {

        "Type": "KubernetesServiceDiscoveryProvider"

      }
    }
}

**Comment by raman-m** [comment] 2024-03-27 13:25
Dear community!
I'm very sorry you had such troubles with K8s provider.
This bug was fixed by PR #1954 
Use version 23.0+

**Closed by raman-m** 2024-03-27 13:25 UTC
