### ISSUE TITLE
Ocelot caching in multiple servers

### ISSUE THREAD

**Issue by PKompis** [ThreeMammals/Ocelot#664] opened 2018-10-16 09:11 UTC
## Expected Behavior / New Feature
When the gateway is installed in multiple servers and in front of those servers a load balancer exists that manages the traffic, there is a need for shared cache, in order to share the same routings between the servers in case of an update (Administration API). Does Ocelot currently supports this feauture? If yes how?

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by TomPallister** [comment] 2018-10-21 16:57
@PKompis at the moment the only option you would have it use consul to store the Ocelot configuration and set it up for the config is shared correctly. Ocelot doesnt keep file configurations in sink (you could make something to do this, I tried using raft but havent had time to make it work properly).

A few people have asked for redis, databases etc but no one has added the feature yet as far as Im aware. It is super easy to do. Just implemented IFileConfigurationRepository for your given datastore. Then register it in services and it will override ocelots default.

**Comment by TomPallister** [comment] 2018-10-21 16:57
I will close this as a duplicate of #654

**Closed by TomPallister** 2018-10-21 16:57 UTC
