### ISSUE TITLE
Rate Limiting works incorrectly if `PeriodTimespan` value is greater than `Period`

### ISSUE THREAD

**Issue by sergio-str** [ThreeMammals/Ocelot#1590] opened 2022-07-28 07:31 UTC
## Expected Behavior
[Rate Limiting](../blob/develop/docs/features/ratelimiting.rst) works as documented for such parameter values:
- **Period**: 1 second
- **PeriodTimespan**:  30 seconds
- **Limit**: 100

**Scenario**:
Request flow, 10-20 requests per sec, should be allowed.

**Status**: not equal to **429**

## Actual Behavior / Motivation for New Feature
With the same parameter values from **Expected Behavior** Ocelot returns status **429** aka "Rate limit exceeded".
It seems this issue caused by code in the `if (entry.HasValue)` block:
https://github.com/ThreeMammals/Ocelot/blob/0b247afdf0c9cba7fd37f603102d151dc7e74487/src/Ocelot/RateLimit/RateLimitCore.cs#L31-L39

Ocelot increments request counter if request has been received in interval: `[FirstRequestTime : FirstRequestTime + PeriodTimeSpan]` 
According to [the documentation](https://ocelot.readthedocs.io/en/latest/features/ratelimiting.html) counter should be incremented if request is in interval: `[FirstRequestTime : FirstRequestTime + Period]`.

## Steps to Reproduce the Problem

1. Set **Rate Limiting** configuration parameters:
  - **Period**: 1 second
  - **PeriodTimespan**: 30 seconds
  - **Limit**: 100
 3. Generate a consequent request flow (10-20 requests per second) for more than 12 seconds
 4. Ensure Ocelot returns status **429**

## Specifications
- Ocelot Version: **Latest**, [**19.0.2**](https://www.nuget.org/packages/Ocelot/19.0.2)
- Feature: [Rate Limiting](https://ocelot.readthedocs.io/en/latest/features/ratelimiting.html)

**Comment by raman-m** [comment] 2023-05-11 13:30
Hi Sergii!

Do not you mind if we collaborate on the issue description first?

**Comment by raman-m** [comment] 2023-05-11 13:35
Check the issue Title please!
Is this title correct?

**Comment by raman-m** [comment] 2023-05-11 13:54
Sergii,
I've changed [**Expected Behavior**](#issue-1320516392) description.
Could you confirm it's correct please?
I need to know we are on the same page.

**Comment by sergio-str** [comment] 2023-05-11 14:02
I think yes. But give me a little time, please, to dive into the context. Also I apologize for inacurate title.

**Comment by raman-m** [comment] 2023-05-11 14:32
So, [bug description](#issue-1320516392) has been changed and updated.
Could you review it plz?

**Comment by raman-m** [comment] 2023-05-12 13:58
@sergio-str Hi Sergii!
Do you accept current description?

**Comment by raman-m** [comment] 2023-06-01 10:42
@sergio-str  Sergii

I would like your checking this bug for the latest build/version which is 19.0.2 and .NET 7.
Your reported Specifications info with "Ocelot Version: 18" is quite outdated.
Please, use the latest package and/or just use top commits from **develop** branch version!

Do not you mind if I change Ocelot Version to **19.0.2** in Specifications paragraph?
That's how I and team can accept this bug after our common validation.
And the team will not accept bugs for old versions, because of outdating.

**Comment by raman-m** [comment] 2023-09-07 16:35
The issue has been [accepted](#event-10309569104) due to open PR #1592 
- #1592

**Comment by MithunChopda** [comment] 2023-11-03 04:57
Also, is it possible to configure RateLimiting globally? Looks like the limits work only when specified at Route level. It's inconvenient to configure Limits for large number of routes.
Limits configured at Route level can then take precedence over Global configuration.

**Comment by raman-m** [comment] 2023-11-03 17:30
> @MithunChopda commented [on Nov 3](#issuecomment-1791894294)

Hi Mithun!
No, impossible! You have to configure Rate Limiter for each route.
Look at this PR #1659 for global [Headers Transformation](https://ocelot.readthedocs.io/en/latest/features/headerstransformation.html). If you will be inspired by this PR, you could open new PR especially for global Rate Liming.

**Comment by raman-m** [comment] 2024-04-30 18:04
> @MithunChopda commented [on Nov 3](#issuecomment-1791894294)

Hi Mithun!
Sorry, I was wrong! **Yes, it is!**
See the docs: [Rate Limiting | Ocelot Own Implementation](https://ocelot.readthedocs.io/en/latest/features/ratelimiting.html#ocelot-own-implementation)

### The quote
> You can also set the following in the **GlobalConfiguration** part of `ocelot.json`:
> ```json
> "GlobalConfiguration": {
>   "BaseUrl": "https://api.mybusiness.com",
>   "RateLimitOptions": {
>     "DisableRateLimitHeaders": false,
>     "QuotaExceededMessage": "Customize Tips!",
>     "HttpStatusCode": 123,
>     "ClientIdHeader": "Test"
>   }
> }
> ```

Hope it helps!

**Closed** 2024-05-07 11:09 UTC
Labels: bug, accepted, high, Rate Limiting, Mar-Apr'24
