### ISSUE TITLE
Ocelot 16.0.1 routing failed when SignalR during WebSocket handshake

### ISSUE THREAD

**Issue by xingwen1987** [ThreeMammals/Ocelot#1283] opened 2020-07-08 02:47 UTC
## Steps to Reproduce the Problem

  1.Use the recommended [configuration of SignalR](https://ocelot.readthedocs.io/en/latest/features/websockets.html?highlight=websocket#websockets) in the official document
![image](https://user-images.githubusercontent.com/15207100/86871041-15ef6400-c10c-11ea-8056-8fc610ea372c.png)
  2.Make sure the SignalR server is available
![image](https://user-images.githubusercontent.com/15207100/86871178-5c44c300-c10c-11ea-8f0b-150292ab0bbb.png)
![image](https://user-images.githubusercontent.com/15207100/86871293-90b87f00-c10c-11ea-9745-b873967fbc37.png)
![image](https://user-images.githubusercontent.com/15207100/86871326-9f069b00-c10c-11ea-82c7-23ecf96f9049.png)
  3.Switch Url to Ocelot's route for SignalR, the following exception occurred
![image](https://user-images.githubusercontent.com/15207100/86871359-b6458880-c10c-11ea-834b-5cceb79e1a6a.png)
![image](https://user-images.githubusercontent.com/15207100/86871390-c52c3b00-c10c-11ea-9cc7-f35c9e25d272.png)
  - Version:16.0.1
  - Platform:.Net Core 3.1

**Comment by ssulleyymmann** [comment] 2020-09-28 10:00
hi,
I am using service discovery, consul and signalr.
I have same problem. Is there any improvement, update or suggest?

**Comment by jlukawska** [comment] 2020-09-28 14:26
UnableToFindDownstreamRouteError when using 16.0.1 version is often caused by "ReRoutes" word in ocelon.json file. The 16.0.1 version requires the word "Routes".

**Comment by ssulleyymmann** [comment] 2020-09-30 08:47
hi jlukawska,

I'm already using it as "routes" but it doesn't work. 

signalr js => 
const connection = new signalR.HubConnectionBuilder()
    .withUrl("http://localhost:5000/socket/xhub", {
        skipNegotiation: true,
        transport: signalR.HttpTransportType.WebSockets
        })
        .configureLogging(signalR.LogLevel.Trace)
        .build();


startup.cs
        public void ConfigureServices(IServiceCollection services)
        {
            services
                .AddOcelot(Configuration)
                .AddConsul()
                .AddConfigStoredInConsul();

            services.AddSwaggerForOcelot(Configuration);
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseWebSockets();
            app.UseOcelot().Wait();
        }

ocelot cong =>
 "Routes": [
    {
      "DownstreamPathTemplate": "/xhub",
      "DownstreamScheme": "http",
      "ServiceName": "x.socket",
      "SwaggerKey": "x.api.socket",
      "UpstreamPathTemplate": "/socket/xhub",
      "UpstreamHttpMethod": [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ],
      "LoadBalancerOptions": {
        "Type": "LeastConnection"
      }
    }
  ]


browser consol =>
[2020-09-30T08:30:51.216Z] Debug: Starting HubConnection.
Utils.ts:178 [2020-09-30T08:30:51.217Z] Debug: Starting connection with transfer format 'Text'.
Utils.ts:178 [2020-09-30T08:30:51.218Z] Trace: (WebSockets transport) Connecting.
WebSocketTransport.ts:64 WebSocket connection to 'ws://localhost:5000/socket/xhub' failed: Error during WebSocket handshake: Unexpected response code: 500
(anonymous) @ WebSocketTransport.ts:64
Utils.ts:168 [2020-09-30T08:30:51.318Z] Error: Failed to start the connection: Error: There was an error with the transport.
Utils.ts:178 [2020-09-30T08:30:51.319Z] Debug: HubConnection failed to start successfully because of error 'Error: There was an error with the transport.'.
x.js:60 Error: There was an error with the transport.
    at WebSocket.webSocket.onerror (WebSocketTransport.ts:85)

**Comment by xingwen1987** [comment] 2020-11-03 10:09
> hi jlukawska,
> 
> I'm already using it as "routes" but it doesn't work.
> 
> signalr js =>
> const connection = new signalR.HubConnectionBuilder()
> .withUrl("http://localhost:5000/socket/xhub", {
> skipNegotiation: true,
> transport: signalR.HttpTransportType.WebSockets
> })
> .configureLogging(signalR.LogLevel.Trace)
> .build();
> 
> startup.cs
> public void ConfigureServices(IServiceCollection services)
> {
> services
> .AddOcelot(Configuration)
> .AddConsul()
> .AddConfigStoredInConsul();
> 
> ```
>         services.AddSwaggerForOcelot(Configuration);
>     }
> 
>     public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
>     {
>         app.UseWebSockets();
>         app.UseOcelot().Wait();
>     }
> ```
> 
> ocelot cong =>
> "Routes": [
> {
> "DownstreamPathTemplate": "/xhub",
> "DownstreamScheme": "http",
> "ServiceName": "x.socket",
> "SwaggerKey": "x.api.socket",
> "UpstreamPathTemplate": "/socket/xhub",
> "UpstreamHttpMethod": [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ],
> "LoadBalancerOptions": {
> "Type": "LeastConnection"
> }
> }
> ]
> 
> browser consol =>
> [2020-09-30T08:30:51.216Z] Debug: Starting HubConnection.
> Utils.ts:178 [2020-09-30T08:30:51.217Z] Debug: Starting connection with transfer format 'Text'.
> Utils.ts:178 [2020-09-30T08:30:51.218Z] Trace: (WebSockets transport) Connecting.
> WebSocketTransport.ts:64 WebSocket connection to 'ws://localhost:5000/socket/xhub' failed: Error during WebSocket handshake: Unexpected response code: 500
> (anonymous) @ WebSocketTransport.ts:64
> Utils.ts:168 [2020-09-30T08:30:51.318Z] Error: Failed to start the connection: Error: There was an error with the transport.
> Utils.ts:178 [2020-09-30T08:30:51.319Z] Debug: HubConnection failed to start successfully because of error 'Error: There was an error with the transport.'.
> x.js:60 Error: There was an error with the transport.
> at WebSocket.webSocket.onerror (WebSocketTransport.ts:85)

https://github.com/dotnet/aspnetcore/issues/10440

this issue give me some idea, in localhost, ocelot works fine, but in docker, route match faild

this is my new issue 

https://github.com/ThreeMammals/Ocelot/issues/1364

**Comment by raman-m** [comment] 2023-05-29 11:43
Hi @xingwen1987 !

> Version: 16.0.1
> Platform: .NET Core 3.1

I guess such spec is outdated during this 2023 year.
Could you upgrade your solution to **.net7** and [v19.0.2](https://www.nuget.org/packages/Ocelot/19.0.2) please?
And let us know the current behavior of the bug please! 🙏 

---
Another question 
> this is my new issue 
> #1364

Thanks for creation new user scenario!
But Is 1364 a duplicate of this 1283 issue?
I see they are both related to SignarR problems, right?
Are you sure they are different root cause issues?

**Comment by raman-m** [comment] 2024-06-15 11:30
### Outdated issue :exclamation:

**Closed by raman-m** 2024-06-15 11:30 UTC
Labels: bug, help wanted, question, large effort, medium effort, needs validation, needs feedback, waiting
