### ISSUE TITLE
UnableToFindServiceDiscoveryProviderError for type "consul " when using type "kube"

### ISSUE THREAD

**Issue by arthursmuller** [ThreeMammals/Ocelot#1529] opened 2021-10-26 03:25 UTC
I have already ran ` kubectl create clusterrolebinding permissive-binding --clusterrole=cluster-admin --user=admin --user=kubelet --group=system:serviceaccounts`

Can someone please tell me whats wrong with it?

When trying to run ocelot inside kubernetes cluster i get this errors
## Error
warn: Ocelot.Responder.Middleware.ResponderMiddleware[0] requestId: 0HMCO5SFMMOIQ:00000002, previousRequestId: no previous request id, message: Error Code: UnableToFindServiceDiscoveryProviderError Message: Unable to find service discovery provider for type: consul errors found in ResponderMiddleware. Setting error response for request path:/externalForumService, request method: GET
```
{
  "Routes": [
    {
      "UpstreamPathTemplate": "/externalForumService/GetAll",
      "DownstreamPathTemplate": "/api/externalforum/v1/forum/GetAll",
      "DownstreamScheme": "http",
      "ServiceName": "externalforum-api-svc",
      "UpstreamHttpMethod": [ "Get" ]
    },
    {
      "UpstreamPathTemplate": "/externalForumService",
      "DownstreamPathTemplate": "/api/externalforum/v1/forum",
      "DownstreamScheme": "http",
      "ServiceName": "externalforum-api-svc",
      "UpstreamHttpMethod": [ "Get" ]
    }
  ],
  "GlobalConfiguration": {
    "ServiceDiscoveryProvider": {
      "Namespace": "propnull",
      "Type": "kube"
    }
  }
}
```

## Service to map
```
apiVersion: v1
kind: Service
metadata:
  name: externalforum-api-svc
  namespace: propnull
spec:
  type: ClusterIP
  selector:
    app: externalforum-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
```

## Specifications

  - Version: 17.0.0
  - Platform: net core 5.0

**Comment by raman-m** [comment] 2024-01-13 17:36
@ggnaegi 
This is strange error.
What do you think?

**Comment by raman-m** [comment] 2024-01-15 10:03
Duplicate of #1527

**Closed** 2024-02-12 09:17 UTC
Labels: bug, accepted, Service Discovery, Nov'23, Kubernetes
